package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Address generated by hbm2java
 */
@XmlRootElement
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idAddress;
	private Taxpayer taxpayer;
	private Integer relateRersonId;
	private String address;
	private Integer addressNum;
	private Integer zip;
	private String city;
	private Integer type;
	private Set<RelatePerson> relatePersons = new HashSet<RelatePerson>(0);

	public Address() {
	}

	public Address(int idAddress) {
		this.idAddress = idAddress;
	}

	public Address(int idAddress, Taxpayer taxpayer, Integer relateRersonId,
			String address, Integer addressNum, Integer zip, String city,
			Integer type, Set<RelatePerson> relatePersons) {
		this.idAddress = idAddress;
		this.taxpayer = taxpayer;
		this.relateRersonId = relateRersonId;
		this.address = address;
		this.addressNum = addressNum;
		this.zip = zip;
		this.city = city;
		this.type = type;
		this.relatePersons = relatePersons;
	}

	public int getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(int idAddress) {
		this.idAddress = idAddress;
	}

	public Taxpayer getTaxpayer() {
		return this.taxpayer;
	}

	public void setTaxpayer(Taxpayer taxpayer) {
		this.taxpayer = taxpayer;
	}

	public Integer getRelateRersonId() {
		return this.relateRersonId;
	}

	public void setRelateRersonId(Integer relateRersonId) {
		this.relateRersonId = relateRersonId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getAddressNum() {
		return this.addressNum;
	}

	public void setAddressNum(Integer addressNum) {
		this.addressNum = addressNum;
	}

	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Set<RelatePerson> getRelatePersons() {
		return this.relatePersons;
	}

	public void setRelatePersons(Set<RelatePerson> relatePersons) {
		this.relatePersons = relatePersons;
	}

}
