package gr.manousos.model;

//Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1 generated by hbm2java
 */
@XmlRootElement
public class E1 implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private E1Id id;
    private Taxpayer taxpayer;
    private String doy;
    private String atid;
    private String taxpayerAddress;
    private Integer isComplete;
    private Integer marriage;
    private Date dateInserted;
    private E1expensesRemovedFromTotalIncome e1expensesRemovedFromTotalIncome;
    private E1incomesReduceTaxes e1incomesReduceTaxes;
    private IncomeTax incomeTax;
    private E1dataFromTaxPayerFolder e1dataFromTaxPayerFolder;
    private E1nauticalincomes e1nauticalincomes;
    private E1reduceTax e1reduceTax;
    private E1taxableIncomes e1taxableIncomes;
    private Set<RelatePerson> relatePersons = new HashSet<RelatePerson>(0);
    private E1taxPayerBankAccount e1taxPayerBankAccount;
    private E1objectiveSpending e1objectiveSpending;
    private E1personDataBorneTaxpayer e1personDataBorneTaxpayer;
    private E1infoData e1infoData;
    private E1prepaidTaxes e1prepaidTaxes;

    public E1() {
    }

    public E1(E1Id id, Taxpayer taxpayer, String doy, String atid,
	    String taxpayerAddress) {
	this.id = id;
	this.taxpayer = taxpayer;
	this.doy = doy;
	this.atid = atid;
	this.taxpayerAddress = taxpayerAddress;
    }

    public E1(E1Id id, Taxpayer taxpayer, String doy, String atid,
	    String taxpayerAddress, Integer isComplete, Integer marriage,
	    Date dateInserted,
	    E1expensesRemovedFromTotalIncome e1expensesRemovedFromTotalIncome,
	    E1incomesReduceTaxes e1incomesReduceTaxes, IncomeTax incomeTax,
	    E1dataFromTaxPayerFolder e1dataFromTaxPayerFolder,
	    E1nauticalincomes e1nauticalincomes, E1reduceTax e1reduceTax,
	    E1taxableIncomes e1taxableIncomes, Set<RelatePerson> relatePersons,
	    E1taxPayerBankAccount e1taxPayerBankAccount,
	    E1objectiveSpending e1objectiveSpending,
	    E1personDataBorneTaxpayer e1personDataBorneTaxpayer,
	    E1infoData e1infoData, E1prepaidTaxes e1prepaidTaxes) {
	this.id = id;
	this.taxpayer = taxpayer;
	this.doy = doy;
	this.atid = atid;
	this.taxpayerAddress = taxpayerAddress;
	this.isComplete = isComplete;
	this.marriage = marriage;
	this.dateInserted = dateInserted;
	this.e1expensesRemovedFromTotalIncome = e1expensesRemovedFromTotalIncome;
	this.e1incomesReduceTaxes = e1incomesReduceTaxes;
	this.incomeTax = incomeTax;
	this.e1dataFromTaxPayerFolder = e1dataFromTaxPayerFolder;
	this.e1nauticalincomes = e1nauticalincomes;
	this.e1reduceTax = e1reduceTax;
	this.e1taxableIncomes = e1taxableIncomes;
	this.relatePersons = relatePersons;
	this.e1taxPayerBankAccount = e1taxPayerBankAccount;
	this.e1objectiveSpending = e1objectiveSpending;
	this.e1personDataBorneTaxpayer = e1personDataBorneTaxpayer;
	this.e1infoData = e1infoData;
	this.e1prepaidTaxes = e1prepaidTaxes;
    }

    public E1Id getId() {
	return this.id;
    }

    public void setId(E1Id id) {
	this.id = id;
    }

    public Taxpayer getTaxpayer() {
	return this.taxpayer;
    }

    public void setTaxpayer(Taxpayer taxpayer) {
	this.taxpayer = taxpayer;
    }

    public String getDoy() {
	return this.doy;
    }

    public void setDoy(String doy) {
	this.doy = doy;
    }

    public String getAtid() {
	return this.atid;
    }

    public void setAtid(String atid) {
	this.atid = atid;
    }

    public String getTaxpayerAddress() {
	return this.taxpayerAddress;
    }

    public void setTaxpayerAddress(String taxpayerAddress) {
	this.taxpayerAddress = taxpayerAddress;
    }

    public Integer getIsComplete() {
	return this.isComplete;
    }

    public void setIsComplete(Integer isComplete) {
	this.isComplete = isComplete;
    }

    public Integer getMarriage() {
	return this.marriage;
    }

    public void setMarriage(Integer marriage) {
	this.marriage = marriage;
    }

    public Date getDateInserted() {
	return this.dateInserted;
    }

    public void setDateInserted(Date dateInserted) {
	this.dateInserted = dateInserted;
    }

    public E1expensesRemovedFromTotalIncome getE1expensesRemovedFromTotalIncome() {
	return this.e1expensesRemovedFromTotalIncome;
    }

    public void setE1expensesRemovedFromTotalIncome(
	    E1expensesRemovedFromTotalIncome e1expensesRemovedFromTotalIncome) {
	this.e1expensesRemovedFromTotalIncome = e1expensesRemovedFromTotalIncome;
    }

    public E1incomesReduceTaxes getE1incomesReduceTaxes() {
	return this.e1incomesReduceTaxes;
    }

    public void setE1incomesReduceTaxes(
	    E1incomesReduceTaxes e1incomesReduceTaxes) {
	this.e1incomesReduceTaxes = e1incomesReduceTaxes;
    }

    public IncomeTax getIncomeTax() {
	return this.incomeTax;
    }

    public void setIncomeTax(IncomeTax incomeTax) {
	this.incomeTax = incomeTax;
    }

    public E1dataFromTaxPayerFolder getE1dataFromTaxPayerFolder() {
	return this.e1dataFromTaxPayerFolder;
    }

    public void setE1dataFromTaxPayerFolder(
	    E1dataFromTaxPayerFolder e1dataFromTaxPayerFolder) {
	this.e1dataFromTaxPayerFolder = e1dataFromTaxPayerFolder;
    }

    public E1nauticalincomes getE1nauticalincomes() {
	return this.e1nauticalincomes;
    }

    public void setE1nauticalincomes(E1nauticalincomes e1nauticalincomes) {
	this.e1nauticalincomes = e1nauticalincomes;
    }

    public E1reduceTax getE1reduceTax() {
	return this.e1reduceTax;
    }

    public void setE1reduceTax(E1reduceTax e1reduceTax) {
	this.e1reduceTax = e1reduceTax;
    }

    public E1taxableIncomes getE1taxableIncomes() {
	return this.e1taxableIncomes;
    }

    public void setE1taxableIncomes(E1taxableIncomes e1taxableIncomes) {
	this.e1taxableIncomes = e1taxableIncomes;
    }

    public Set<RelatePerson> getRelatePersons() {
	return this.relatePersons;
    }

    public void setRelatePersons(Set<RelatePerson> relatePersons) {
	this.relatePersons = relatePersons;
    }

    public E1taxPayerBankAccount getE1taxPayerBankAccount() {
	return this.e1taxPayerBankAccount;
    }

    public void setE1taxPayerBankAccount(
	    E1taxPayerBankAccount e1taxPayerBankAccount) {
	this.e1taxPayerBankAccount = e1taxPayerBankAccount;
    }

    public E1objectiveSpending getE1objectiveSpending() {
	return this.e1objectiveSpending;
    }

    public void setE1objectiveSpending(E1objectiveSpending e1objectiveSpending) {
	this.e1objectiveSpending = e1objectiveSpending;
    }

    public E1personDataBorneTaxpayer getE1personDataBorneTaxpayer() {
	return this.e1personDataBorneTaxpayer;
    }

    public void setE1personDataBorneTaxpayer(
	    E1personDataBorneTaxpayer e1personDataBorneTaxpayer) {
	this.e1personDataBorneTaxpayer = e1personDataBorneTaxpayer;
    }

    public E1infoData getE1infoData() {
	return this.e1infoData;
    }

    public void setE1infoData(E1infoData e1infoData) {
	this.e1infoData = e1infoData;
    }

    public E1prepaidTaxes getE1prepaidTaxes() {
	return this.e1prepaidTaxes;
    }

    public void setE1prepaidTaxes(E1prepaidTaxes e1prepaidTaxes) {
	this.e1prepaidTaxes = e1prepaidTaxes;
    }

}
