package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1dataFromTaxPayerFolder generated by hbm2java
 */
@XmlRootElement
public class E1dataFromTaxPayerFolder implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idE1dataFromTaxPayerFolder;
	private Float _901;
	private Float _902;
	private Float _903;
	private Float _904;
	private Float _341;
	private Float _342;
	private Float _745;
	private Float _746;
	private Float _995;
	private Float _996;
	private Float _997;
	private Float _998;
	private Float _959;
	private Float _960;
	private Float _743;
	private Float _744;
	private Float _323;
	private Float _324;
	private Float _399;
	private Float _400;
	private Float _907;
	private Float _908;
	private Float _985;
	private Float _986;
	private Float _987;
	private Float _988;
	private Float _989;
	private Float _990;
	private Set<E1> e1s = new HashSet<E1>(0);

	public E1dataFromTaxPayerFolder() {
	}

	public E1dataFromTaxPayerFolder(Float _901, Float _902, Float _903,
			Float _904, Float _341, Float _342, Float _745, Float _746,
			Float _995, Float _996, Float _997, Float _998, Float _959,
			Float _960, Float _743, Float _744, Float _323, Float _324,
			Float _399, Float _400, Float _907, Float _908, Float _985,
			Float _986, Float _987, Float _988, Float _989, Float _990,
			Set<E1> e1s) {
		this._901 = _901;
		this._902 = _902;
		this._903 = _903;
		this._904 = _904;
		this._341 = _341;
		this._342 = _342;
		this._745 = _745;
		this._746 = _746;
		this._995 = _995;
		this._996 = _996;
		this._997 = _997;
		this._998 = _998;
		this._959 = _959;
		this._960 = _960;
		this._743 = _743;
		this._744 = _744;
		this._323 = _323;
		this._324 = _324;
		this._399 = _399;
		this._400 = _400;
		this._907 = _907;
		this._908 = _908;
		this._985 = _985;
		this._986 = _986;
		this._987 = _987;
		this._988 = _988;
		this._989 = _989;
		this._990 = _990;
		this.e1s = e1s;
	}

	public Integer getIdE1dataFromTaxPayerFolder() {
		return this.idE1dataFromTaxPayerFolder;
	}

	public void setIdE1dataFromTaxPayerFolder(Integer idE1dataFromTaxPayerFolder) {
		this.idE1dataFromTaxPayerFolder = idE1dataFromTaxPayerFolder;
	}

	public Float get901() {
		return this._901;
	}

	public void set901(Float _901) {
		this._901 = _901;
	}

	public Float get902() {
		return this._902;
	}

	public void set902(Float _902) {
		this._902 = _902;
	}

	public Float get903() {
		return this._903;
	}

	public void set903(Float _903) {
		this._903 = _903;
	}

	public Float get904() {
		return this._904;
	}

	public void set904(Float _904) {
		this._904 = _904;
	}

	public Float get341() {
		return this._341;
	}

	public void set341(Float _341) {
		this._341 = _341;
	}

	public Float get342() {
		return this._342;
	}

	public void set342(Float _342) {
		this._342 = _342;
	}

	public Float get745() {
		return this._745;
	}

	public void set745(Float _745) {
		this._745 = _745;
	}

	public Float get746() {
		return this._746;
	}

	public void set746(Float _746) {
		this._746 = _746;
	}

	public Float get995() {
		return this._995;
	}

	public void set995(Float _995) {
		this._995 = _995;
	}

	public Float get996() {
		return this._996;
	}

	public void set996(Float _996) {
		this._996 = _996;
	}

	public Float get997() {
		return this._997;
	}

	public void set997(Float _997) {
		this._997 = _997;
	}

	public Float get998() {
		return this._998;
	}

	public void set998(Float _998) {
		this._998 = _998;
	}

	public Float get959() {
		return this._959;
	}

	public void set959(Float _959) {
		this._959 = _959;
	}

	public Float get960() {
		return this._960;
	}

	public void set960(Float _960) {
		this._960 = _960;
	}

	public Float get743() {
		return this._743;
	}

	public void set743(Float _743) {
		this._743 = _743;
	}

	public Float get744() {
		return this._744;
	}

	public void set744(Float _744) {
		this._744 = _744;
	}

	public Float get323() {
		return this._323;
	}

	public void set323(Float _323) {
		this._323 = _323;
	}

	public Float get324() {
		return this._324;
	}

	public void set324(Float _324) {
		this._324 = _324;
	}

	public Float get399() {
		return this._399;
	}

	public void set399(Float _399) {
		this._399 = _399;
	}

	public Float get400() {
		return this._400;
	}

	public void set400(Float _400) {
		this._400 = _400;
	}

	public Float get907() {
		return this._907;
	}

	public void set907(Float _907) {
		this._907 = _907;
	}

	public Float get908() {
		return this._908;
	}

	public void set908(Float _908) {
		this._908 = _908;
	}

	public Float get985() {
		return this._985;
	}

	public void set985(Float _985) {
		this._985 = _985;
	}

	public Float get986() {
		return this._986;
	}

	public void set986(Float _986) {
		this._986 = _986;
	}

	public Float get987() {
		return this._987;
	}

	public void set987(Float _987) {
		this._987 = _987;
	}

	public Float get988() {
		return this._988;
	}

	public void set988(Float _988) {
		this._988 = _988;
	}

	public Float get989() {
		return this._989;
	}

	public void set989(Float _989) {
		this._989 = _989;
	}

	public Float get990() {
		return this._990;
	}

	public void set990(Float _990) {
		this._990 = _990;
	}

	public Set<E1> getE1s() {
		return this.e1s;
	}

	public void setE1s(Set<E1> e1s) {
		this.e1s = e1s;
	}

}