package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1expensesRemovedFromTotalIncome generated by hbm2java
 */
@XmlRootElement
public class E1expensesRemovedFromTotalIncome implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idE1expensesRemovedFromTotalIncome;
	private Float _049;
	private Float _051;
	private Float _052;
	private Float _053;
	private Float _054;
	private Float _057;
	private Float _058;
	private Float _031;
	private Float _032;
	private Float _059;
	private Float _060;
	private Float _075;
	private Float _076;
	private Float _061;
	private Float _062;
	private Float _071;
	private Float _063;
	private Float _064;
	private Float _069;
	private Float _070;
	private String rentalForFamilyOwnerName1;
	private String _801;
	private Integer _092;
	private Float _091;
	private Integer _097;
	private Float _811;
	private Float _812;
	private String rentalForFamilyOwnerName2;
	private String _802;
	private Integer _094;
	private Float _093;
	private Integer _098;
	private Float _813;
	private Float _814;
	private String rentalForFamilyOwnerName3;
	private String _803;
	private Integer _096;
	private Float _095;
	private Float _099;
	private Float _815;
	private Float _816;
	private String rentalForStudyOwnerName1;
	private String _804;
	private Float _817;
	private String rentalForStudyOwnerName2;
	private String _805;
	private Float _819;
	private String rentalForStudyOwnerName3;
	private String _806;
	private Float _821;
	private String rentalForStudyOwnerName4;
	private String _807;
	private Float _823;
	private Float _073;
	private Float _074;
	private Float _089;
	private Float _090;
	private Float _087;
	private Float _088;
	private Float _079;
	private Float _080;
	private Float _084;
	private Float _085;
	private Float _077;
	private Float _078;
	private Float _663;
	private Float _664;
	private Integer _033;
	private Integer _034;
	private Integer _035;
	private Integer _036;
	private Set<E1> e1s = new HashSet<E1>(0);

	public E1expensesRemovedFromTotalIncome() {
	}

	public E1expensesRemovedFromTotalIncome(Float _049, Float _051, Float _052,
			Float _053, Float _054, Float _057, Float _058, Float _031,
			Float _032, Float _059, Float _060, Float _075, Float _076,
			Float _061, Float _062, Float _071, Float _063, Float _064,
			Float _069, Float _070, String rentalForFamilyOwnerName1,
			String _801, Integer _092, Float _091, Integer _097, Float _811,
			Float _812, String rentalForFamilyOwnerName2, String _802,
			Integer _094, Float _093, Integer _098, Float _813, Float _814,
			String rentalForFamilyOwnerName3, String _803, Integer _096,
			Float _095, Float _099, Float _815, Float _816,
			String rentalForStudyOwnerName1, String _804, Float _817,
			String rentalForStudyOwnerName2, String _805, Float _819,
			String rentalForStudyOwnerName3, String _806, Float _821,
			String rentalForStudyOwnerName4, String _807, Float _823,
			Float _073, Float _074, Float _089, Float _090, Float _087,
			Float _088, Float _079, Float _080, Float _084, Float _085,
			Float _077, Float _078, Float _663, Float _664, Integer _033,
			Integer _034, Integer _035, Integer _036, Set<E1> e1s) {
		this._049 = _049;
		this._051 = _051;
		this._052 = _052;
		this._053 = _053;
		this._054 = _054;
		this._057 = _057;
		this._058 = _058;
		this._031 = _031;
		this._032 = _032;
		this._059 = _059;
		this._060 = _060;
		this._075 = _075;
		this._076 = _076;
		this._061 = _061;
		this._062 = _062;
		this._071 = _071;
		this._063 = _063;
		this._064 = _064;
		this._069 = _069;
		this._070 = _070;
		this.rentalForFamilyOwnerName1 = rentalForFamilyOwnerName1;
		this._801 = _801;
		this._092 = _092;
		this._091 = _091;
		this._097 = _097;
		this._811 = _811;
		this._812 = _812;
		this.rentalForFamilyOwnerName2 = rentalForFamilyOwnerName2;
		this._802 = _802;
		this._094 = _094;
		this._093 = _093;
		this._098 = _098;
		this._813 = _813;
		this._814 = _814;
		this.rentalForFamilyOwnerName3 = rentalForFamilyOwnerName3;
		this._803 = _803;
		this._096 = _096;
		this._095 = _095;
		this._099 = _099;
		this._815 = _815;
		this._816 = _816;
		this.rentalForStudyOwnerName1 = rentalForStudyOwnerName1;
		this._804 = _804;
		this._817 = _817;
		this.rentalForStudyOwnerName2 = rentalForStudyOwnerName2;
		this._805 = _805;
		this._819 = _819;
		this.rentalForStudyOwnerName3 = rentalForStudyOwnerName3;
		this._806 = _806;
		this._821 = _821;
		this.rentalForStudyOwnerName4 = rentalForStudyOwnerName4;
		this._807 = _807;
		this._823 = _823;
		this._073 = _073;
		this._074 = _074;
		this._089 = _089;
		this._090 = _090;
		this._087 = _087;
		this._088 = _088;
		this._079 = _079;
		this._080 = _080;
		this._084 = _084;
		this._085 = _085;
		this._077 = _077;
		this._078 = _078;
		this._663 = _663;
		this._664 = _664;
		this._033 = _033;
		this._034 = _034;
		this._035 = _035;
		this._036 = _036;
		this.e1s = e1s;
	}

	public Integer getIdE1expensesRemovedFromTotalIncome() {
		return this.idE1expensesRemovedFromTotalIncome;
	}

	public void setIdE1expensesRemovedFromTotalIncome(
			Integer idE1expensesRemovedFromTotalIncome) {
		this.idE1expensesRemovedFromTotalIncome = idE1expensesRemovedFromTotalIncome;
	}

	public Float get049() {
		return this._049;
	}

	public void set049(Float _049) {
		this._049 = _049;
	}

	public Float get051() {
		return this._051;
	}

	public void set051(Float _051) {
		this._051 = _051;
	}

	public Float get052() {
		return this._052;
	}

	public void set052(Float _052) {
		this._052 = _052;
	}

	public Float get053() {
		return this._053;
	}

	public void set053(Float _053) {
		this._053 = _053;
	}

	public Float get054() {
		return this._054;
	}

	public void set054(Float _054) {
		this._054 = _054;
	}

	public Float get057() {
		return this._057;
	}

	public void set057(Float _057) {
		this._057 = _057;
	}

	public Float get058() {
		return this._058;
	}

	public void set058(Float _058) {
		this._058 = _058;
	}

	public Float get031() {
		return this._031;
	}

	public void set031(Float _031) {
		this._031 = _031;
	}

	public Float get032() {
		return this._032;
	}

	public void set032(Float _032) {
		this._032 = _032;
	}

	public Float get059() {
		return this._059;
	}

	public void set059(Float _059) {
		this._059 = _059;
	}

	public Float get060() {
		return this._060;
	}

	public void set060(Float _060) {
		this._060 = _060;
	}

	public Float get075() {
		return this._075;
	}

	public void set075(Float _075) {
		this._075 = _075;
	}

	public Float get076() {
		return this._076;
	}

	public void set076(Float _076) {
		this._076 = _076;
	}

	public Float get061() {
		return this._061;
	}

	public void set061(Float _061) {
		this._061 = _061;
	}

	public Float get062() {
		return this._062;
	}

	public void set062(Float _062) {
		this._062 = _062;
	}

	public Float get071() {
		return this._071;
	}

	public void set071(Float _071) {
		this._071 = _071;
	}

	public Float get063() {
		return this._063;
	}

	public void set063(Float _063) {
		this._063 = _063;
	}

	public Float get064() {
		return this._064;
	}

	public void set064(Float _064) {
		this._064 = _064;
	}

	public Float get069() {
		return this._069;
	}

	public void set069(Float _069) {
		this._069 = _069;
	}

	public Float get070() {
		return this._070;
	}

	public void set070(Float _070) {
		this._070 = _070;
	}

	public String getRentalForFamilyOwnerName1() {
		return this.rentalForFamilyOwnerName1;
	}

	public void setRentalForFamilyOwnerName1(String rentalForFamilyOwnerName1) {
		this.rentalForFamilyOwnerName1 = rentalForFamilyOwnerName1;
	}

	public String get801() {
		return this._801;
	}

	public void set801(String _801) {
		this._801 = _801;
	}

	public Integer get092() {
		return this._092;
	}

	public void set092(Integer _092) {
		this._092 = _092;
	}

	public Float get091() {
		return this._091;
	}

	public void set091(Float _091) {
		this._091 = _091;
	}

	public Integer get097() {
		return this._097;
	}

	public void set097(Integer _097) {
		this._097 = _097;
	}

	public Float get811() {
		return this._811;
	}

	public void set811(Float _811) {
		this._811 = _811;
	}

	public Float get812() {
		return this._812;
	}

	public void set812(Float _812) {
		this._812 = _812;
	}

	public String getRentalForFamilyOwnerName2() {
		return this.rentalForFamilyOwnerName2;
	}

	public void setRentalForFamilyOwnerName2(String rentalForFamilyOwnerName2) {
		this.rentalForFamilyOwnerName2 = rentalForFamilyOwnerName2;
	}

	public String get802() {
		return this._802;
	}

	public void set802(String _802) {
		this._802 = _802;
	}

	public Integer get094() {
		return this._094;
	}

	public void set094(Integer _094) {
		this._094 = _094;
	}

	public Float get093() {
		return this._093;
	}

	public void set093(Float _093) {
		this._093 = _093;
	}

	public Integer get098() {
		return this._098;
	}

	public void set098(Integer _098) {
		this._098 = _098;
	}

	public Float get813() {
		return this._813;
	}

	public void set813(Float _813) {
		this._813 = _813;
	}

	public Float get814() {
		return this._814;
	}

	public void set814(Float _814) {
		this._814 = _814;
	}

	public String getRentalForFamilyOwnerName3() {
		return this.rentalForFamilyOwnerName3;
	}

	public void setRentalForFamilyOwnerName3(String rentalForFamilyOwnerName3) {
		this.rentalForFamilyOwnerName3 = rentalForFamilyOwnerName3;
	}

	public String get803() {
		return this._803;
	}

	public void set803(String _803) {
		this._803 = _803;
	}

	public Integer get096() {
		return this._096;
	}

	public void set096(Integer _096) {
		this._096 = _096;
	}

	public Float get095() {
		return this._095;
	}

	public void set095(Float _095) {
		this._095 = _095;
	}

	public Float get099() {
		return this._099;
	}

	public void set099(Float _099) {
		this._099 = _099;
	}

	public Float get815() {
		return this._815;
	}

	public void set815(Float _815) {
		this._815 = _815;
	}

	public Float get816() {
		return this._816;
	}

	public void set816(Float _816) {
		this._816 = _816;
	}

	public String getRentalForStudyOwnerName1() {
		return this.rentalForStudyOwnerName1;
	}

	public void setRentalForStudyOwnerName1(String rentalForStudyOwnerName1) {
		this.rentalForStudyOwnerName1 = rentalForStudyOwnerName1;
	}

	public String get804() {
		return this._804;
	}

	public void set804(String _804) {
		this._804 = _804;
	}

	public Float get817() {
		return this._817;
	}

	public void set817(Float _817) {
		this._817 = _817;
	}

	public String getRentalForStudyOwnerName2() {
		return this.rentalForStudyOwnerName2;
	}

	public void setRentalForStudyOwnerName2(String rentalForStudyOwnerName2) {
		this.rentalForStudyOwnerName2 = rentalForStudyOwnerName2;
	}

	public String get805() {
		return this._805;
	}

	public void set805(String _805) {
		this._805 = _805;
	}

	public Float get819() {
		return this._819;
	}

	public void set819(Float _819) {
		this._819 = _819;
	}

	public String getRentalForStudyOwnerName3() {
		return this.rentalForStudyOwnerName3;
	}

	public void setRentalForStudyOwnerName3(String rentalForStudyOwnerName3) {
		this.rentalForStudyOwnerName3 = rentalForStudyOwnerName3;
	}

	public String get806() {
		return this._806;
	}

	public void set806(String _806) {
		this._806 = _806;
	}

	public Float get821() {
		return this._821;
	}

	public void set821(Float _821) {
		this._821 = _821;
	}

	public String getRentalForStudyOwnerName4() {
		return this.rentalForStudyOwnerName4;
	}

	public void setRentalForStudyOwnerName4(String rentalForStudyOwnerName4) {
		this.rentalForStudyOwnerName4 = rentalForStudyOwnerName4;
	}

	public String get807() {
		return this._807;
	}

	public void set807(String _807) {
		this._807 = _807;
	}

	public Float get823() {
		return this._823;
	}

	public void set823(Float _823) {
		this._823 = _823;
	}

	public Float get073() {
		return this._073;
	}

	public void set073(Float _073) {
		this._073 = _073;
	}

	public Float get074() {
		return this._074;
	}

	public void set074(Float _074) {
		this._074 = _074;
	}

	public Float get089() {
		return this._089;
	}

	public void set089(Float _089) {
		this._089 = _089;
	}

	public Float get090() {
		return this._090;
	}

	public void set090(Float _090) {
		this._090 = _090;
	}

	public Float get087() {
		return this._087;
	}

	public void set087(Float _087) {
		this._087 = _087;
	}

	public Float get088() {
		return this._088;
	}

	public void set088(Float _088) {
		this._088 = _088;
	}

	public Float get079() {
		return this._079;
	}

	public void set079(Float _079) {
		this._079 = _079;
	}

	public Float get080() {
		return this._080;
	}

	public void set080(Float _080) {
		this._080 = _080;
	}

	public Float get084() {
		return this._084;
	}

	public void set084(Float _084) {
		this._084 = _084;
	}

	public Float get085() {
		return this._085;
	}

	public void set085(Float _085) {
		this._085 = _085;
	}

	public Float get077() {
		return this._077;
	}

	public void set077(Float _077) {
		this._077 = _077;
	}

	public Float get078() {
		return this._078;
	}

	public void set078(Float _078) {
		this._078 = _078;
	}

	public Float get663() {
		return this._663;
	}

	public void set663(Float _663) {
		this._663 = _663;
	}

	public Float get664() {
		return this._664;
	}

	public void set664(Float _664) {
		this._664 = _664;
	}

	public Integer get033() {
		return this._033;
	}

	public void set033(Integer _033) {
		this._033 = _033;
	}

	public Integer get034() {
		return this._034;
	}

	public void set034(Integer _034) {
		this._034 = _034;
	}

	public Integer get035() {
		return this._035;
	}

	public void set035(Integer _035) {
		this._035 = _035;
	}

	public Integer get036() {
		return this._036;
	}

	public void set036(Integer _036) {
		this._036 = _036;
	}

	public Set<E1> getE1s() {
		return this.e1s;
	}

	public void setE1s(Set<E1> e1s) {
		this.e1s = e1s;
	}
}
