package gr.manousos.model;

//Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1expensesRemovedFromTotalIncome generated by hbm2java
 */
@XmlRootElement
public class E1expensesRemovedFromTotalIncome implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private E1expensesRemovedFromTotalIncomeId id;
    private E1 e1;
    private Float _049;
    private Float _051;
    private Float _052;
    private Float _053;
    private Float _054;
    private Float _057;
    private Float _058;
    private Float _031;
    private Float _032;
    private Float _059;
    private Float _060;
    private Float _075;
    private Float _076;
    private Float _061;
    private Float _062;
    private Float _071;
    private Float _063;
    private Float _064;
    private Float _069;
    private Float _070;
    private String rentalForFamilyOwnerName1;
    private String _801;
    private Integer _092;
    private Float _091;
    private Integer _097;
    private Float _811;
    private Float _812;
    private String rentalForFamilyOwnerName2;
    private String _802;
    private Integer _094;
    private Float _093;
    private Integer _098;
    private Float _813;
    private Float _814;
    private String rentalForFamilyOwnerName3;
    private String _803;
    private Integer _096;
    private Float _095;
    private Float _099;
    private Float _815;
    private Float _816;
    private String rentalForStudyOwnerName1;
    private String _804;
    private Float _817;
    private String rentalForStudyOwnerName2;
    private String _805;
    private Float _819;
    private String rentalForStudyOwnerName3;
    private String _806;
    private Float _821;
    private String rentalForStudyOwnerName4;
    private String _807;
    private Float _823;
    private Float _073;
    private Float _074;
    private Float _089;
    private Float _090;
    private Float _087;
    private Float _088;
    private Float _079;
    private Float _080;
    private Float _081;
    private Float _082;
    private Float _083;
    private Float _084;
    private Float _085;
    private Float _077;
    private Float _078;
    private Float _663;
    private Float _664;
    private Integer _033;
    private Integer _034;
    private Integer _035;
    private Integer _036;

    public E1expensesRemovedFromTotalIncome() {
    }

    public E1expensesRemovedFromTotalIncome(E1 e1) {
	this.e1 = e1;
    }

    public E1expensesRemovedFromTotalIncome(E1 e1, Float _049, Float _051,
	    Float _052, Float _053, Float _054, Float _057, Float _058,
	    Float _031, Float _032, Float _059, Float _060, Float _075,
	    Float _076, Float _061, Float _062, Float _071, Float _063,
	    Float _064, Float _069, Float _070,
	    String rentalForFamilyOwnerName1, String _801, Integer _092,
	    Float _091, Integer _097, Float _811, Float _812,
	    String rentalForFamilyOwnerName2, String _802, Integer _094,
	    Float _093, Integer _098, Float _813, Float _814,
	    String rentalForFamilyOwnerName3, String _803, Integer _096,
	    Float _095, Float _099, Float _815, Float _816,
	    String rentalForStudyOwnerName1, String _804, Float _817,
	    String rentalForStudyOwnerName2, String _805, Float _819,
	    String rentalForStudyOwnerName3, String _806, Float _821,
	    String rentalForStudyOwnerName4, String _807, Float _823,
	    Float _073, Float _074, Float _089, Float _090, Float _087,
	    Float _088, Float _079, Float _080, Float _081, Float _082,
	    Float _083, Float _084, Float _085, Float _077, Float _078,
	    Float _663, Float _664, Integer _033, Integer _034, Integer _035,
	    Integer _036) {
	this.e1 = e1;
	this._049 = _049;
	this._051 = _051;
	this._052 = _052;
	this._053 = _053;
	this._054 = _054;
	this._057 = _057;
	this._058 = _058;
	this._031 = _031;
	this._032 = _032;
	this._059 = _059;
	this._060 = _060;
	this._075 = _075;
	this._076 = _076;
	this._061 = _061;
	this._062 = _062;
	this._071 = _071;
	this._063 = _063;
	this._064 = _064;
	this._069 = _069;
	this._070 = _070;
	this.rentalForFamilyOwnerName1 = rentalForFamilyOwnerName1;
	this._801 = _801;
	this._092 = _092;
	this._091 = _091;
	this._097 = _097;
	this._811 = _811;
	this._812 = _812;
	this.rentalForFamilyOwnerName2 = rentalForFamilyOwnerName2;
	this._802 = _802;
	this._094 = _094;
	this._093 = _093;
	this._098 = _098;
	this._813 = _813;
	this._814 = _814;
	this.rentalForFamilyOwnerName3 = rentalForFamilyOwnerName3;
	this._803 = _803;
	this._096 = _096;
	this._095 = _095;
	this._099 = _099;
	this._815 = _815;
	this._816 = _816;
	this.rentalForStudyOwnerName1 = rentalForStudyOwnerName1;
	this._804 = _804;
	this._817 = _817;
	this.rentalForStudyOwnerName2 = rentalForStudyOwnerName2;
	this._805 = _805;
	this._819 = _819;
	this.rentalForStudyOwnerName3 = rentalForStudyOwnerName3;
	this._806 = _806;
	this._821 = _821;
	this.rentalForStudyOwnerName4 = rentalForStudyOwnerName4;
	this._807 = _807;
	this._823 = _823;
	this._073 = _073;
	this._074 = _074;
	this._089 = _089;
	this._090 = _090;
	this._087 = _087;
	this._088 = _088;
	this._079 = _079;
	this._080 = _080;
	this._081 = _081;
	this._082 = _082;
	this._083 = _083;
	this._084 = _084;
	this._085 = _085;
	this._077 = _077;
	this._078 = _078;
	this._663 = _663;
	this._664 = _664;
	this._033 = _033;
	this._034 = _034;
	this._035 = _035;
	this._036 = _036;
    }

    public E1expensesRemovedFromTotalIncomeId getId() {
	return this.id;
    }

    public void setId(E1expensesRemovedFromTotalIncomeId id) {
	this.id = id;
    }

    public E1 getE1() {
	return this.e1;
    }

    public void setE1(E1 e1) {
	this.e1 = e1;
    }

    public Float get_049() {
	return _049;
    }

    public void set_049(Float _049) {
	this._049 = _049;
    }

    public Float get_051() {
	return _051;
    }

    public void set_051(Float _051) {
	this._051 = _051;
    }

    public Float get_052() {
	return _052;
    }

    public void set_052(Float _052) {
	this._052 = _052;
    }

    public Float get_053() {
	return _053;
    }

    public void set_053(Float _053) {
	this._053 = _053;
    }

    public Float get_054() {
	return _054;
    }

    public void set_054(Float _054) {
	this._054 = _054;
    }

    public Float get_057() {
	return _057;
    }

    public void set_057(Float _057) {
	this._057 = _057;
    }

    public Float get_058() {
	return _058;
    }

    public void set_058(Float _058) {
	this._058 = _058;
    }

    public Float get_031() {
	return _031;
    }

    public void set_031(Float _031) {
	this._031 = _031;
    }

    public Float get_032() {
	return _032;
    }

    public void set_032(Float _032) {
	this._032 = _032;
    }

    public Float get_059() {
	return _059;
    }

    public void set_059(Float _059) {
	this._059 = _059;
    }

    public Float get_060() {
	return _060;
    }

    public void set_060(Float _060) {
	this._060 = _060;
    }

    public Float get_075() {
	return _075;
    }

    public void set_075(Float _075) {
	this._075 = _075;
    }

    public Float get_076() {
	return _076;
    }

    public void set_076(Float _076) {
	this._076 = _076;
    }

    public Float get_061() {
	return _061;
    }

    public void set_061(Float _061) {
	this._061 = _061;
    }

    public Float get_062() {
	return _062;
    }

    public void set_062(Float _062) {
	this._062 = _062;
    }

    public Float get_071() {
	return _071;
    }

    public void set_071(Float _071) {
	this._071 = _071;
    }

    public Float get_063() {
	return _063;
    }

    public void set_063(Float _063) {
	this._063 = _063;
    }

    public Float get_064() {
	return _064;
    }

    public void set_064(Float _064) {
	this._064 = _064;
    }

    public Float get_069() {
	return _069;
    }

    public void set_069(Float _069) {
	this._069 = _069;
    }

    public Float get_070() {
	return _070;
    }

    public void set_070(Float _070) {
	this._070 = _070;
    }

    public String getRentalForFamilyOwnerName1() {
	return rentalForFamilyOwnerName1;
    }

    public void setRentalForFamilyOwnerName1(String rentalForFamilyOwnerName1) {
	this.rentalForFamilyOwnerName1 = rentalForFamilyOwnerName1;
    }

    public String get_801() {
	return _801;
    }

    public void set_801(String _801) {
	this._801 = _801;
    }

    public Integer get_092() {
	return _092;
    }

    public void set_092(Integer _092) {
	this._092 = _092;
    }

    public Float get_091() {
	return _091;
    }

    public void set_091(Float _091) {
	this._091 = _091;
    }

    public Integer get_097() {
	return _097;
    }

    public void set_097(Integer _097) {
	this._097 = _097;
    }

    public Float get_811() {
	return _811;
    }

    public void set_811(Float _811) {
	this._811 = _811;
    }

    public Float get_812() {
	return _812;
    }

    public void set_812(Float _812) {
	this._812 = _812;
    }

    public String getRentalForFamilyOwnerName2() {
	return rentalForFamilyOwnerName2;
    }

    public void setRentalForFamilyOwnerName2(String rentalForFamilyOwnerName2) {
	this.rentalForFamilyOwnerName2 = rentalForFamilyOwnerName2;
    }

    public String get_802() {
	return _802;
    }

    public void set_802(String _802) {
	this._802 = _802;
    }

    public Integer get_094() {
	return _094;
    }

    public void set_094(Integer _094) {
	this._094 = _094;
    }

    public Float get_093() {
	return _093;
    }

    public void set_093(Float _093) {
	this._093 = _093;
    }

    public Integer get_098() {
	return _098;
    }

    public void set_098(Integer _098) {
	this._098 = _098;
    }

    public Float get_813() {
	return _813;
    }

    public void set_813(Float _813) {
	this._813 = _813;
    }

    public Float get_814() {
	return _814;
    }

    public void set_814(Float _814) {
	this._814 = _814;
    }

    public String getRentalForFamilyOwnerName3() {
	return rentalForFamilyOwnerName3;
    }

    public void setRentalForFamilyOwnerName3(String rentalForFamilyOwnerName3) {
	this.rentalForFamilyOwnerName3 = rentalForFamilyOwnerName3;
    }

    public String get_803() {
	return _803;
    }

    public void set_803(String _803) {
	this._803 = _803;
    }

    public Integer get_096() {
	return _096;
    }

    public void set_096(Integer _096) {
	this._096 = _096;
    }

    public Float get_095() {
	return _095;
    }

    public void set_095(Float _095) {
	this._095 = _095;
    }

    public Float get_099() {
	return _099;
    }

    public void set_099(Float _099) {
	this._099 = _099;
    }

    public Float get_815() {
	return _815;
    }

    public void set_815(Float _815) {
	this._815 = _815;
    }

    public Float get_816() {
	return _816;
    }

    public void set_816(Float _816) {
	this._816 = _816;
    }

    public String getRentalForStudyOwnerName1() {
	return rentalForStudyOwnerName1;
    }

    public void setRentalForStudyOwnerName1(String rentalForStudyOwnerName1) {
	this.rentalForStudyOwnerName1 = rentalForStudyOwnerName1;
    }

    public String get_804() {
	return _804;
    }

    public void set_804(String _804) {
	this._804 = _804;
    }

    public Float get_817() {
	return _817;
    }

    public void set_817(Float _817) {
	this._817 = _817;
    }

    public String getRentalForStudyOwnerName2() {
	return rentalForStudyOwnerName2;
    }

    public void setRentalForStudyOwnerName2(String rentalForStudyOwnerName2) {
	this.rentalForStudyOwnerName2 = rentalForStudyOwnerName2;
    }

    public String get_805() {
	return _805;
    }

    public void set_805(String _805) {
	this._805 = _805;
    }

    public Float get_819() {
	return _819;
    }

    public void set_819(Float _819) {
	this._819 = _819;
    }

    public String getRentalForStudyOwnerName3() {
	return rentalForStudyOwnerName3;
    }

    public void setRentalForStudyOwnerName3(String rentalForStudyOwnerName3) {
	this.rentalForStudyOwnerName3 = rentalForStudyOwnerName3;
    }

    public String get_806() {
	return _806;
    }

    public void set_806(String _806) {
	this._806 = _806;
    }

    public Float get_821() {
	return _821;
    }

    public void set_821(Float _821) {
	this._821 = _821;
    }

    public String getRentalForStudyOwnerName4() {
	return rentalForStudyOwnerName4;
    }

    public void setRentalForStudyOwnerName4(String rentalForStudyOwnerName4) {
	this.rentalForStudyOwnerName4 = rentalForStudyOwnerName4;
    }

    public String get_807() {
	return _807;
    }

    public void set_807(String _807) {
	this._807 = _807;
    }

    public Float get_823() {
	return _823;
    }

    public void set_823(Float _823) {
	this._823 = _823;
    }

    public Float get_073() {
	return _073;
    }

    public void set_073(Float _073) {
	this._073 = _073;
    }

    public Float get_074() {
	return _074;
    }

    public void set_074(Float _074) {
	this._074 = _074;
    }

    public Float get_089() {
	return _089;
    }

    public void set_089(Float _089) {
	this._089 = _089;
    }

    public Float get_090() {
	return _090;
    }

    public void set_090(Float _090) {
	this._090 = _090;
    }

    public Float get_087() {
	return _087;
    }

    public void set_087(Float _087) {
	this._087 = _087;
    }

    public Float get_088() {
	return _088;
    }

    public void set_088(Float _088) {
	this._088 = _088;
    }

    public Float get_079() {
	return _079;
    }

    public void set_079(Float _079) {
	this._079 = _079;
    }

    public Float get_080() {
	return _080;
    }

    public void set_080(Float _080) {
	this._080 = _080;
    }

    public Float get_081() {
	return _081;
    }

    public void set_081(Float _081) {
	this._081 = _081;
    }

    public Float get_082() {
	return _082;
    }

    public void set_082(Float _082) {
	this._082 = _082;
    }

    public Float get_083() {
	return _083;
    }

    public void set_083(Float _083) {
	this._083 = _083;
    }

    public Float get_084() {
	return _084;
    }

    public void set_084(Float _084) {
	this._084 = _084;
    }

    public Float get_085() {
	return _085;
    }

    public void set_085(Float _085) {
	this._085 = _085;
    }

    public Float get_077() {
	return _077;
    }

    public void set_077(Float _077) {
	this._077 = _077;
    }

    public Float get_078() {
	return _078;
    }

    public void set_078(Float _078) {
	this._078 = _078;
    }

    public Float get_663() {
	return _663;
    }

    public void set_663(Float _663) {
	this._663 = _663;
    }

    public Float get_664() {
	return _664;
    }

    public void set_664(Float _664) {
	this._664 = _664;
    }

    public Integer get_033() {
	return _033;
    }

    public void set_033(Integer _033) {
	this._033 = _033;
    }

    public Integer get_034() {
	return _034;
    }

    public void set_034(Integer _034) {
	this._034 = _034;
    }

    public Integer get_035() {
	return _035;
    }

    public void set_035(Integer _035) {
	this._035 = _035;
    }

    public Integer get_036() {
	return _036;
    }

    public void set_036(Integer _036) {
	this._036 = _036;
    }

}
