package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1incomesReduceTaxes generated by hbm2java
 */
@XmlRootElement
public class E1incomesReduceTaxes implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer idE1incomesReduceTaxes;
    private Float _655;
    private Float _656;
    private Float _693;
    private Float _694;
    private Float _659;
    private Float _660;
    private Float _657;
    private Float _658;
    private Float _661;
    private Float _662;
    private Float _431;
    private Float _432;
    private Float _433;
    private Float _434;
    private Float _305;
    private Float _306;
    private Float _477;
    private Float _478;
    private String lessorName1;
    private String _790;
    private Float _795;
    private String lassorName2;
    private String _791;
    private Float _796;
    private Float _793;
    private Float _794;
    private Float _615;
    private String _616;
    private String lassorNameForStudent;
    private String _417;
    private Float areaStudentHouse;
    private Float _419;
    private Float _420;
    private Float _735;
    private Float _736;
    private Float _781;
    private Float _782;
    private Float _783;
    private Float _784;
    private Float _787;
    private Float _788;
    private Set<E1> e1s = new HashSet<E1>(0);

    public E1incomesReduceTaxes() {
    }

    public E1incomesReduceTaxes(Float _655, Float _656, Float _693, Float _694,
	    Float _659, Float _660, Float _657, Float _658, Float _661,
	    Float _662, Float _431, Float _432, Float _433, Float _434,
	    Float _305, Float _306, Float _477, Float _478, String lessorName1,
	    String _790, Float _795, String lassorName2, String _791,
	    Float _796, Float _793, Float _794, Float _615, String _616,
	    String lassorNameForStudent, String _417, Float areaStudentHouse,
	    Float _419, Float _420, Float _735, Float _736, Float _781,
	    Float _782, Float _783, Float _784, Float _787, Float _788,
	    Set<E1> e1s) {
	this._655 = _655;
	this._656 = _656;
	this._693 = _693;
	this._694 = _694;
	this._659 = _659;
	this._660 = _660;
	this._657 = _657;
	this._658 = _658;
	this._661 = _661;
	this._662 = _662;
	this._431 = _431;
	this._432 = _432;
	this._433 = _433;
	this._434 = _434;
	this._305 = _305;
	this._306 = _306;
	this._477 = _477;
	this._478 = _478;
	this.lessorName1 = lessorName1;
	this._790 = _790;
	this._795 = _795;
	this.lassorName2 = lassorName2;
	this._791 = _791;
	this._796 = _796;
	this._793 = _793;
	this._794 = _794;
	this._615 = _615;
	this._616 = _616;
	this.lassorNameForStudent = lassorNameForStudent;
	this._417 = _417;
	this.areaStudentHouse = areaStudentHouse;
	this._419 = _419;
	this._420 = _420;
	this._735 = _735;
	this._736 = _736;
	this._781 = _781;
	this._782 = _782;
	this._783 = _783;
	this._784 = _784;
	this._787 = _787;
	this._788 = _788;
	this.e1s = e1s;
    }

    public Integer getIdE1incomesReduceTaxes() {
	return idE1incomesReduceTaxes;
    }

    public void setIdE1incomesReduceTaxes(Integer idE1incomesReduceTaxes) {
	this.idE1incomesReduceTaxes = idE1incomesReduceTaxes;
    }

    public Float get_655() {
	return _655;
    }

    public void set_655(Float _655) {
	this._655 = _655;
    }

    public Float get_656() {
	return _656;
    }

    public void set_656(Float _656) {
	this._656 = _656;
    }

    public Float get_693() {
	return _693;
    }

    public void set_693(Float _693) {
	this._693 = _693;
    }

    public Float get_694() {
	return _694;
    }

    public void set_694(Float _694) {
	this._694 = _694;
    }

    public Float get_659() {
	return _659;
    }

    public void set_659(Float _659) {
	this._659 = _659;
    }

    public Float get_660() {
	return _660;
    }

    public void set_660(Float _660) {
	this._660 = _660;
    }

    public Float get_657() {
	return _657;
    }

    public void set_657(Float _657) {
	this._657 = _657;
    }

    public Float get_658() {
	return _658;
    }

    public void set_658(Float _658) {
	this._658 = _658;
    }

    public Float get_661() {
	return _661;
    }

    public void set_661(Float _661) {
	this._661 = _661;
    }

    public Float get_662() {
	return _662;
    }

    public void set_662(Float _662) {
	this._662 = _662;
    }

    public Float get_431() {
	return _431;
    }

    public void set_431(Float _431) {
	this._431 = _431;
    }

    public Float get_432() {
	return _432;
    }

    public void set_432(Float _432) {
	this._432 = _432;
    }

    public Float get_433() {
	return _433;
    }

    public void set_433(Float _433) {
	this._433 = _433;
    }

    public Float get_434() {
	return _434;
    }

    public void set_434(Float _434) {
	this._434 = _434;
    }

    public Float get_305() {
	return _305;
    }

    public void set_305(Float _305) {
	this._305 = _305;
    }

    public Float get_306() {
	return _306;
    }

    public void set_306(Float _306) {
	this._306 = _306;
    }

    public Float get_477() {
	return _477;
    }

    public void set_477(Float _477) {
	this._477 = _477;
    }

    public Float get_478() {
	return _478;
    }

    public void set_478(Float _478) {
	this._478 = _478;
    }

    public String getLessorName1() {
	return lessorName1;
    }

    public void setLessorName1(String lessorName1) {
	this.lessorName1 = lessorName1;
    }

    public String get_790() {
	return _790;
    }

    public void set_790(String _790) {
	this._790 = _790;
    }

    public Float get_795() {
	return _795;
    }

    public void set_795(Float _795) {
	this._795 = _795;
    }

    public String getLassorName2() {
	return lassorName2;
    }

    public void setLassorName2(String lassorName2) {
	this.lassorName2 = lassorName2;
    }

    public String get_791() {
	return _791;
    }

    public void set_791(String _791) {
	this._791 = _791;
    }

    public Float get_796() {
	return _796;
    }

    public void set_796(Float _796) {
	this._796 = _796;
    }

    public Float get_793() {
	return _793;
    }

    public void set_793(Float _793) {
	this._793 = _793;
    }

    public Float get_794() {
	return _794;
    }

    public void set_794(Float _794) {
	this._794 = _794;
    }

    public Float get_615() {
	return _615;
    }

    public void set_615(Float _615) {
	this._615 = _615;
    }

    public String get_616() {
	return _616;
    }

    public void set_616(String _616) {
	this._616 = _616;
    }

    public String getLassorNameForStudent() {
	return lassorNameForStudent;
    }

    public void setLassorNameForStudent(String lassorNameForStudent) {
	this.lassorNameForStudent = lassorNameForStudent;
    }

    public String get_417() {
	return _417;
    }

    public void set_417(String _417) {
	this._417 = _417;
    }

    public Float getAreaStudentHouse() {
	return areaStudentHouse;
    }

    public void setAreaStudentHouse(Float areaStudentHouse) {
	this.areaStudentHouse = areaStudentHouse;
    }

    public Float get_419() {
	return _419;
    }

    public void set_419(Float _419) {
	this._419 = _419;
    }

    public Float get_420() {
	return _420;
    }

    public void set_420(Float _420) {
	this._420 = _420;
    }

    public Float get_735() {
	return _735;
    }

    public void set_735(Float _735) {
	this._735 = _735;
    }

    public Float get_736() {
	return _736;
    }

    public void set_736(Float _736) {
	this._736 = _736;
    }

    public Float get_781() {
	return _781;
    }

    public void set_781(Float _781) {
	this._781 = _781;
    }

    public Float get_782() {
	return _782;
    }

    public void set_782(Float _782) {
	this._782 = _782;
    }

    public Float get_783() {
	return _783;
    }

    public void set_783(Float _783) {
	this._783 = _783;
    }

    public Float get_784() {
	return _784;
    }

    public void set_784(Float _784) {
	this._784 = _784;
    }

    public Float get_787() {
	return _787;
    }

    public void set_787(Float _787) {
	this._787 = _787;
    }

    public Float get_788() {
	return _788;
    }

    public void set_788(Float _788) {
	this._788 = _788;
    }

    public Set<E1> getE1s() {
	return this.e1s;
    }

    public void setE1s(Set<E1> e1s) {
	this.e1s = e1s;
    }

}
