package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1objectiveSpending generated by hbm2java
 */
@XmlRootElement
public class E1objectiveSpending implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idE1objectiveSpending;
	private String _205;
	private String houseAddr1;
	private String floor1;
	private Integer _203;
	private Integer _240;
	private Float _211;
	private Float _212;
	private Float _213;
	private Float _214;
	private Integer _215;
	private Float _216;
	private String houseAddr2;
	private String floor2;
	private Integer _207;
	private Integer _241;
	private Float _218;
	private Float _219;
	private Float _220;
	private Float _221;
	private Integer _222;
	private Float _223;
	private String houseAddr3;
	private String floor3;
	private Integer _209;
	private Integer _242;
	private Float _225;
	private Float _226;
	private Float _227;
	private Float _228;
	private Integer _229;
	private Float _230;
	private Float _707;
	private Float _708;
	private String afm1;
	private String _750;
	private Integer _703;
	private Integer _761;
	private Float _771;
	private Integer _775;
	private String afm2;
	private String _751;
	private Integer _704;
	private Integer _762;
	private Float _772;
	private Integer _776;
	private String afm3;
	private String _752;
	private Integer _705;
	private Integer _763;
	private Float _773;
	private Integer _777;
	private String afm4;
	private String _753;
	private Integer _706;
	private Integer _764;
	private Float _774;
	private Integer _778;
	private Float _851;
	private Float _852;
	private Float _853;
	private Float _854;
	private Float _855;
	private Float _856;
	private Float _857;
	private Float _858;
	private String shippingName1;
	private String shippingRegister1;
	private String shippingCountry1;
	private Integer sailShip1;
	private Integer accommodationSpace1;
	private Float percentPrincipalCoOwner1;
	private Float percentWifeCoOwner1;
	private Integer firstRegister1;
	private Integer ownershipMonths1;
	private Float _747;
	private String shippingName2;
	private String shippingRegister2;
	private String shippingCountry2;
	private Integer sailShip2;
	private Integer accommodationSpace2;
	private Float percentPrincipalCoOwner2;
	private Float percentWifeCoOwner2;
	private Integer firstRegister2;
	private Integer ownershipMonths2;
	private Float _748;
	private Float _711;
	private Float _712;
	private Float _713;
	private Float _714;
	private Float _731;
	private Float _732;
	private String aircraftRegisterData;
	private String aircraftType;
	private String aircraftSn;
	private String airportBase;
	private Integer aircraftOwnerShip;
	private Integer aircraftPowerLibres;
	private Integer aircraftFirstRegister;
	private Float _715;
	private Float _716;
	private Float _767;
	private Float poolPrincipalCoOwnerOutdoor;
	private Float poolWifeCoOwnerOutdoor;
	private Float _768;
	private Float poolPrincipalCoOwnerIndoor;
	private Float poolWifeCoOwnerIndoor;
	private Float _765;
	private Float _766;
	private Float _769;
	private Float _770;
	private Float _719;
	private Float _720;
	private Float _721;
	private Float _722;
	private Float _723;
	private Float _724;
	private Float _725;
	private Float _726;
	private Float _727;
	private Float _728;
	private Set<E1> e1s = new HashSet<E1>(0);

	public E1objectiveSpending() {
	}

	public E1objectiveSpending(String _205, String houseAddr1, String floor1,
			Integer _203, Integer _240, Float _211, Float _212, Float _213,
			Float _214, Integer _215, Float _216, String houseAddr2,
			String floor2, Integer _207, Integer _241, Float _218, Float _219,
			Float _220, Float _221, Integer _222, Float _223,
			String houseAddr3, String floor3, Integer _209, Integer _242,
			Float _225, Float _226, Float _227, Float _228, Integer _229,
			Float _230, Float _707, Float _708, String afm1, String _750,
			Integer _703, Integer _761, Float _771, Integer _775, String afm2,
			String _751, Integer _704, Integer _762, Float _772, Integer _776,
			String afm3, String _752, Integer _705, Integer _763, Float _773,
			Integer _777, String afm4, String _753, Integer _706, Integer _764,
			Float _774, Integer _778, Float _851, Float _852, Float _853,
			Float _854, Float _855, Float _856, Float _857, Float _858,
			String shippingName1, String shippingRegister1,
			String shippingCountry1, Integer sailShip1,
			Integer accommodationSpace1, Float percentPrincipalCoOwner1,
			Float percentWifeCoOwner1, Integer firstRegister1,
			Integer ownershipMonths1, Float _747, String shippingName2,
			String shippingRegister2, String shippingCountry2,
			Integer sailShip2, Integer accommodationSpace2,
			Float percentPrincipalCoOwner2, Float percentWifeCoOwner2,
			Integer firstRegister2, Integer ownershipMonths2, Float _748,
			Float _711, Float _712, Float _713, Float _714, Float _731,
			Float _732, String aircraftRegisterData, String aircraftType,
			String aircraftSn, String airportBase, Integer aircraftOwnerShip,
			Integer aircraftPowerLibres, Integer aircraftFirstRegister,
			Float _715, Float _716, Float _767,
			Float poolPrincipalCoOwnerOutdoor, Float poolWifeCoOwnerOutdoor,
			Float _768, Float poolPrincipalCoOwnerIndoor,
			Float poolWifeCoOwnerIndoor, Float _765, Float _766, Float _769,
			Float _770, Float _719, Float _720, Float _721, Float _722,
			Float _723, Float _724, Float _725, Float _726, Float _727,
			Float _728, Set<E1> e1s) {
		this._205 = _205;
		this.houseAddr1 = houseAddr1;
		this.floor1 = floor1;
		this._203 = _203;
		this._240 = _240;
		this._211 = _211;
		this._212 = _212;
		this._213 = _213;
		this._214 = _214;
		this._215 = _215;
		this._216 = _216;
		this.houseAddr2 = houseAddr2;
		this.floor2 = floor2;
		this._207 = _207;
		this._241 = _241;
		this._218 = _218;
		this._219 = _219;
		this._220 = _220;
		this._221 = _221;
		this._222 = _222;
		this._223 = _223;
		this.houseAddr3 = houseAddr3;
		this.floor3 = floor3;
		this._209 = _209;
		this._242 = _242;
		this._225 = _225;
		this._226 = _226;
		this._227 = _227;
		this._228 = _228;
		this._229 = _229;
		this._230 = _230;
		this._707 = _707;
		this._708 = _708;
		this.afm1 = afm1;
		this._750 = _750;
		this._703 = _703;
		this._761 = _761;
		this._771 = _771;
		this._775 = _775;
		this.afm2 = afm2;
		this._751 = _751;
		this._704 = _704;
		this._762 = _762;
		this._772 = _772;
		this._776 = _776;
		this.afm3 = afm3;
		this._752 = _752;
		this._705 = _705;
		this._763 = _763;
		this._773 = _773;
		this._777 = _777;
		this.afm4 = afm4;
		this._753 = _753;
		this._706 = _706;
		this._764 = _764;
		this._774 = _774;
		this._778 = _778;
		this._851 = _851;
		this._852 = _852;
		this._853 = _853;
		this._854 = _854;
		this._855 = _855;
		this._856 = _856;
		this._857 = _857;
		this._858 = _858;
		this.shippingName1 = shippingName1;
		this.shippingRegister1 = shippingRegister1;
		this.shippingCountry1 = shippingCountry1;
		this.sailShip1 = sailShip1;
		this.accommodationSpace1 = accommodationSpace1;
		this.percentPrincipalCoOwner1 = percentPrincipalCoOwner1;
		this.percentWifeCoOwner1 = percentWifeCoOwner1;
		this.firstRegister1 = firstRegister1;
		this.ownershipMonths1 = ownershipMonths1;
		this._747 = _747;
		this.shippingName2 = shippingName2;
		this.shippingRegister2 = shippingRegister2;
		this.shippingCountry2 = shippingCountry2;
		this.sailShip2 = sailShip2;
		this.accommodationSpace2 = accommodationSpace2;
		this.percentPrincipalCoOwner2 = percentPrincipalCoOwner2;
		this.percentWifeCoOwner2 = percentWifeCoOwner2;
		this.firstRegister2 = firstRegister2;
		this.ownershipMonths2 = ownershipMonths2;
		this._748 = _748;
		this._711 = _711;
		this._712 = _712;
		this._713 = _713;
		this._714 = _714;
		this._731 = _731;
		this._732 = _732;
		this.aircraftRegisterData = aircraftRegisterData;
		this.aircraftType = aircraftType;
		this.aircraftSn = aircraftSn;
		this.airportBase = airportBase;
		this.aircraftOwnerShip = aircraftOwnerShip;
		this.aircraftPowerLibres = aircraftPowerLibres;
		this.aircraftFirstRegister = aircraftFirstRegister;
		this._715 = _715;
		this._716 = _716;
		this._767 = _767;
		this.poolPrincipalCoOwnerOutdoor = poolPrincipalCoOwnerOutdoor;
		this.poolWifeCoOwnerOutdoor = poolWifeCoOwnerOutdoor;
		this._768 = _768;
		this.poolPrincipalCoOwnerIndoor = poolPrincipalCoOwnerIndoor;
		this.poolWifeCoOwnerIndoor = poolWifeCoOwnerIndoor;
		this._765 = _765;
		this._766 = _766;
		this._769 = _769;
		this._770 = _770;
		this._719 = _719;
		this._720 = _720;
		this._721 = _721;
		this._722 = _722;
		this._723 = _723;
		this._724 = _724;
		this._725 = _725;
		this._726 = _726;
		this._727 = _727;
		this._728 = _728;
		this.e1s = e1s;
	}

	public Integer getIdE1objectiveSpending() {
		return this.idE1objectiveSpending;
	}

	public void setIdE1objectiveSpending(Integer idE1objectiveSpending) {
		this.idE1objectiveSpending = idE1objectiveSpending;
	}

	public String get205() {
		return this._205;
	}

	public void set205(String _205) {
		this._205 = _205;
	}

	public String getHouseAddr1() {
		return this.houseAddr1;
	}

	public void setHouseAddr1(String houseAddr1) {
		this.houseAddr1 = houseAddr1;
	}

	public String getFloor1() {
		return floor1;
	}

	public void setFloor1(String floor1) {
		this.floor1 = floor1;
	}

	public Integer get203() {
		return this._203;
	}

	public void set203(Integer _203) {
		this._203 = _203;
	}

	public Integer get240() {
		return this._240;
	}

	public void set240(Integer _240) {
		this._240 = _240;
	}

	public Float _get211() {
		return this._211;
	}

	public void set211(Float _211) {
		this._211 = _211;
	}

	public Float get212() {
		return this._212;
	}

	public void set212(Float _212) {
		this._212 = _212;
	}

	public Float get213() {
		return this._213;
	}

	public void set213(Float _213) {
		this._213 = _213;
	}

	public Float get214() {
		return this._214;
	}

	public void set214(Float _214) {
		this._214 = _214;
	}

	public Integer get215() {
		return this._215;
	}

	public void set215(Integer _215) {
		this._215 = _215;
	}

	public Float get216() {
		return this._216;
	}

	public void set216(Float _216) {
		this._216 = _216;
	}

	public String getHouseAddr2() {
		return this.houseAddr2;
	}

	public void setHouseAddr2(String houseAddr2) {
		this.houseAddr2 = houseAddr2;
	}

	public String getFloor2() {
		return floor2;
	}

	public void setFloor2(String floor2) {
		this.floor2 = floor2;
	}

	public Integer get207() {
		return this._207;
	}

	public void set207(Integer _207) {
		this._207 = _207;
	}

	public Integer get241() {
		return this._241;
	}

	public void set241(Integer _241) {
		this._241 = _241;
	}

	public Float get218() {
		return this._218;
	}

	public void set218(Float _218) {
		this._218 = _218;
	}

	public Float get219() {
		return this._219;
	}

	public void set219(Float _219) {
		this._219 = _219;
	}

	public Float get220() {
		return this._220;
	}

	public void set220(Float _220) {
		this._220 = _220;
	}

	public Float get221() {
		return this._221;
	}

	public void set221(Float _221) {
		this._221 = _221;
	}

	public Integer get222() {
		return this._222;
	}

	public void set222(Integer _222) {
		this._222 = _222;
	}

	public Float get223() {
		return this._223;
	}

	public void set223(Float _223) {
		this._223 = _223;
	}

	public String getHouseAddr3() {
		return this.houseAddr3;
	}

	public void setHouseAddr3(String houseAddr3) {
		this.houseAddr3 = houseAddr3;
	}

	public String getFloor3() {
		return floor3;
	}

	public void setFloor3(String floor3) {
		this.floor3 = floor3;
	}

	public Integer get209() {
		return this._209;
	}

	public void set209(Integer _209) {
		this._209 = _209;
	}

	public Integer get242() {
		return this._242;
	}

	public void set242(Integer _242) {
		this._242 = _242;
	}

	public Float get225() {
		return this._225;
	}

	public void set225(Float _225) {
		this._225 = _225;
	}

	public Float get226() {
		return this._226;
	}

	public void set226(Float _226) {
		this._226 = _226;
	}

	public Float get227() {
		return this._227;
	}

	public void set227(Float _227) {
		this._227 = _227;
	}

	public Float get228() {
		return this._228;
	}

	public void set228(Float _228) {
		this._228 = _228;
	}

	public Integer get229() {
		return this._229;
	}

	public void set229(Integer _229) {
		this._229 = _229;
	}

	public Float get230() {
		return this._230;
	}

	public void set230(Float _230) {
		this._230 = _230;
	}

	public Float get707() {
		return this._707;
	}

	public void set707(Float _707) {
		this._707 = _707;
	}

	public Float get708() {
		return this._708;
	}

	public void set708(Float _708) {
		this._708 = _708;
	}

	public String getAfm1() {
		return this.afm1;
	}

	public void setAfm1(String afm1) {
		this.afm1 = afm1;
	}

	public String get750() {
		return this._750;
	}

	public void set750(String _750) {
		this._750 = _750;
	}

	public Integer get703() {
		return this._703;
	}

	public void set703(Integer _703) {
		this._703 = _703;
	}

	public Integer get761() {
		return this._761;
	}

	public void set761(Integer _761) {
		this._761 = _761;
	}

	public Float get771() {
		return this._771;
	}

	public void set771(Float _771) {
		this._771 = _771;
	}

	public Integer get775() {
		return this._775;
	}

	public void set775(Integer _775) {
		this._775 = _775;
	}

	public String getAfm2() {
		return this.afm2;
	}

	public void setAfm2(String afm2) {
		this.afm2 = afm2;
	}

	public String get751() {
		return this._751;
	}

	public void set751(String _751) {
		this._751 = _751;
	}

	public Integer get704() {
		return this._704;
	}

	public void set704(Integer _704) {
		this._704 = _704;
	}

	public Integer get762() {
		return this._762;
	}

	public void set762(Integer _762) {
		this._762 = _762;
	}

	public Float get772() {
		return this._772;
	}

	public void set772(Float _772) {
		this._772 = _772;
	}

	public Integer get776() {
		return this._776;
	}

	public void set776(Integer _776) {
		this._776 = _776;
	}

	public String getAfm3() {
		return this.afm3;
	}

	public void setAfm3(String afm3) {
		this.afm3 = afm3;
	}

	public String get752() {
		return this._752;
	}

	public void set752(String _752) {
		this._752 = _752;
	}

	public Integer get705() {
		return this._705;
	}

	public void set705(Integer _705) {
		this._705 = _705;
	}

	public Integer get763() {
		return this._763;
	}

	public void set763(Integer _763) {
		this._763 = _763;
	}

	public Float get773() {
		return this._773;
	}

	public void set773(Float _773) {
		this._773 = _773;
	}

	public Integer get777() {
		return this._777;
	}

	public void set777(Integer _777) {
		this._777 = _777;
	}

	public String getAfm4() {
		return this.afm4;
	}

	public void setAfm4(String afm4) {
		this.afm4 = afm4;
	}

	public String get753() {
		return this._753;
	}

	public void set753(String _753) {
		this._753 = _753;
	}

	public Integer get706() {
		return this._706;
	}

	public void set706(Integer _706) {
		this._706 = _706;
	}

	public Integer get764() {
		return this._764;
	}

	public void set764(Integer _764) {
		this._764 = _764;
	}

	public Float get774() {
		return this._774;
	}

	public void set774(Float _774) {
		this._774 = _774;
	}

	public Integer get778() {
		return this._778;
	}

	public void set778(Integer _778) {
		this._778 = _778;
	}

	public Float get851() {
		return this._851;
	}

	public void set851(Float _851) {
		this._851 = _851;
	}

	public Float get852() {
		return this._852;
	}

	public void set852(Float _852) {
		this._852 = _852;
	}

	public Float get853() {
		return this._853;
	}

	public void set853(Float _853) {
		this._853 = _853;
	}

	public Float get854() {
		return this._854;
	}

	public void set854(Float _854) {
		this._854 = _854;
	}

	public Float get855() {
		return this._855;
	}

	public void set855(Float _855) {
		this._855 = _855;
	}

	public Float get856() {
		return this._856;
	}

	public void set856(Float _856) {
		this._856 = _856;
	}

	public Float get857() {
		return this._857;
	}

	public void set857(Float _857) {
		this._857 = _857;
	}

	public Float get858() {
		return this._858;
	}

	public void set858(Float _858) {
		this._858 = _858;
	}

	public String getShippingName1() {
		return this.shippingName1;
	}

	public void setShippingName1(String shippingName1) {
		this.shippingName1 = shippingName1;
	}

	public String getShippingRegister1() {
		return this.shippingRegister1;
	}

	public void setShippingRegister1(String shippingRegister1) {
		this.shippingRegister1 = shippingRegister1;
	}

	public String getShippingCountry1() {
		return this.shippingCountry1;
	}

	public void setShippingCountry1(String shippingCountry1) {
		this.shippingCountry1 = shippingCountry1;
	}

	public Integer getSailShip1() {
		return this.sailShip1;
	}

	public void setSailShip1(Integer sailShip1) {
		this.sailShip1 = sailShip1;
	}

	public Integer getAccommodationSpace1() {
		return this.accommodationSpace1;
	}

	public void setAccommodationSpace1(Integer accommodationSpace1) {
		this.accommodationSpace1 = accommodationSpace1;
	}

	public Float getPercentPrincipalCoOwner1() {
		return this.percentPrincipalCoOwner1;
	}

	public void setPercentPrincipalCoOwner1(Float percentPrincipalCoOwner1) {
		this.percentPrincipalCoOwner1 = percentPrincipalCoOwner1;
	}

	public Float getPercentWifeCoOwner1() {
		return this.percentWifeCoOwner1;
	}

	public void setPercentWifeCoOwner1(Float percentWifeCoOwner1) {
		this.percentWifeCoOwner1 = percentWifeCoOwner1;
	}

	public Integer getFirstRegister1() {
		return this.firstRegister1;
	}

	public void setFirstRegister1(Integer firstRegister1) {
		this.firstRegister1 = firstRegister1;
	}

	public Integer getOwnershipMonths1() {
		return this.ownershipMonths1;
	}

	public void setOwnershipMonths1(Integer ownershipMonths1) {
		this.ownershipMonths1 = ownershipMonths1;
	}

	public Float get747() {
		return this._747;
	}

	public void set747(Float _747) {
		this._747 = _747;
	}

	public String getShippingName2() {
		return this.shippingName2;
	}

	public void setShippingName2(String shippingName2) {
		this.shippingName2 = shippingName2;
	}

	public String getShippingRegister2() {
		return this.shippingRegister2;
	}

	public void setShippingRegister2(String shippingRegister2) {
		this.shippingRegister2 = shippingRegister2;
	}

	public String getShippingCountry2() {
		return this.shippingCountry2;
	}

	public void setShippingCountry2(String shippingCountry2) {
		this.shippingCountry2 = shippingCountry2;
	}

	public Integer getSailShip2() {
		return this.sailShip2;
	}

	public void setSailShip2(Integer sailShip2) {
		this.sailShip2 = sailShip2;
	}

	public Integer getAccommodationSpace2() {
		return this.accommodationSpace2;
	}

	public void setAccommodationSpace2(Integer accommodationSpace2) {
		this.accommodationSpace2 = accommodationSpace2;
	}

	public Float getPercentPrincipalCoOwner2() {
		return this.percentPrincipalCoOwner2;
	}

	public void setPercentPrincipalCoOwner2(Float percentPrincipalCoOwner2) {
		this.percentPrincipalCoOwner2 = percentPrincipalCoOwner2;
	}

	public Float getPercentWifeCoOwner2() {
		return this.percentWifeCoOwner2;
	}

	public void setPercentWifeCoOwner2(Float percentWifeCoOwner2) {
		this.percentWifeCoOwner2 = percentWifeCoOwner2;
	}

	public Integer getFirstRegister2() {
		return this.firstRegister2;
	}

	public void setFirstRegister2(Integer firstRegister2) {
		this.firstRegister2 = firstRegister2;
	}

	public Integer getOwnershipMonths2() {
		return this.ownershipMonths2;
	}

	public void setOwnershipMonths2(Integer ownershipMonths2) {
		this.ownershipMonths2 = ownershipMonths2;
	}

	public Float get748() {
		return this._748;
	}

	public void set748(Float _748) {
		this._748 = _748;
	}

	public Float get711() {
		return this._711;
	}

	public void set711(Float _711) {
		this._711 = _711;
	}

	public Float get712() {
		return this._712;
	}

	public void set712(Float _712) {
		this._712 = _712;
	}

	public Float get713() {
		return this._713;
	}

	public void set713(Float _713) {
		this._713 = _713;
	}

	public Float get714() {
		return this._714;
	}

	public void set714(Float _714) {
		this._714 = _714;
	}

	public Float get731() {
		return this._731;
	}

	public void set731(Float _731) {
		this._731 = _731;
	}

	public Float get732() {
		return this._732;
	}

	public void set732(Float _732) {
		this._732 = _732;
	}

	public String getAircraftRegisterData() {
		return this.aircraftRegisterData;
	}

	public void setAircraftRegisterData(String aircraftRegisterData) {
		this.aircraftRegisterData = aircraftRegisterData;
	}

	public String getAircraftType() {
		return this.aircraftType;
	}

	public void setAircraftType(String aircraftType) {
		this.aircraftType = aircraftType;
	}

	public String getAircraftSn() {
		return this.aircraftSn;
	}

	public void setAircraftSn(String aircraftSn) {
		this.aircraftSn = aircraftSn;
	}

	public String getAirportBase() {
		return this.airportBase;
	}

	public void setAirportBase(String airportBase) {
		this.airportBase = airportBase;
	}

	public Integer getAircraftOwnerShip() {
		return this.aircraftOwnerShip;
	}

	public void setAircraftOwnerShip(Integer aircraftOwnerShip) {
		this.aircraftOwnerShip = aircraftOwnerShip;
	}

	public Integer getAircraftPowerLibres() {
		return this.aircraftPowerLibres;
	}

	public void setAircraftPowerLibres(Integer aircraftPowerLibres) {
		this.aircraftPowerLibres = aircraftPowerLibres;
	}

	public Integer getAircraftFirstRegister() {
		return this.aircraftFirstRegister;
	}

	public void setAircraftFirstRegister(Integer aircraftFirstRegister) {
		this.aircraftFirstRegister = aircraftFirstRegister;
	}

	public Float get715() {
		return this._715;
	}

	public void set715(Float _715) {
		this._715 = _715;
	}

	public Float get716() {
		return this._716;
	}

	public void set716(Float _716) {
		this._716 = _716;
	}

	public Float get767() {
		return this._767;
	}

	public void set767(Float _767) {
		this._767 = _767;
	}

	public Float getPoolPrincipalCoOwnerOutdoor() {
		return this.poolPrincipalCoOwnerOutdoor;
	}

	public void setPoolPrincipalCoOwnerOutdoor(Float poolPrincipalCoOwnerOutdoor) {
		this.poolPrincipalCoOwnerOutdoor = poolPrincipalCoOwnerOutdoor;
	}

	public Float getPoolWifeCoOwnerOutdoor() {
		return this.poolWifeCoOwnerOutdoor;
	}

	public void setPoolWifeCoOwnerOutdoor(Float poolWifeCoOwnerOutdoor) {
		this.poolWifeCoOwnerOutdoor = poolWifeCoOwnerOutdoor;
	}

	public Float get768() {
		return this._768;
	}

	public void set768(Float _768) {
		this._768 = _768;
	}

	public Float getPoolPrincipalCoOwnerIndoor() {
		return this.poolPrincipalCoOwnerIndoor;
	}

	public void setPoolPrincipalCoOwnerIndoor(Float poolPrincipalCoOwnerIndoor) {
		this.poolPrincipalCoOwnerIndoor = poolPrincipalCoOwnerIndoor;
	}

	public Float getPoolWifeCoOwnerIndoor() {
		return this.poolWifeCoOwnerIndoor;
	}

	public void setPoolWifeCoOwnerIndoor(Float poolWifeCoOwnerIndoor) {
		this.poolWifeCoOwnerIndoor = poolWifeCoOwnerIndoor;
	}

	public Float get765() {
		return this._765;
	}

	public void set765(Float _765) {
		this._765 = _765;
	}

	public Float get766() {
		return this._766;
	}

	public void set766(Float _766) {
		this._766 = _766;
	}

	public Float get769() {
		return this._769;
	}

	public void set769(Float _769) {
		this._769 = _769;
	}

	public Float get770() {
		return this._770;
	}

	public void set770(Float _770) {
		this._770 = _770;
	}

	public Float get719() {
		return this._719;
	}

	public void set719(Float _719) {
		this._719 = _719;
	}

	public Float get720() {
		return this._720;
	}

	public void set720(Float _720) {
		this._720 = _720;
	}

	public Float get721() {
		return this._721;
	}

	public void set721(Float _721) {
		this._721 = _721;
	}

	public Float get722() {
		return this._722;
	}

	public void set722(Float _722) {
		this._722 = _722;
	}

	public Float get723() {
		return this._723;
	}

	public void set723(Float _723) {
		this._723 = _723;
	}

	public Float get724() {
		return this._724;
	}

	public void set724(Float _724) {
		this._724 = _724;
	}

	public Float get725() {
		return this._725;
	}

	public void set725(Float _725) {
		this._725 = _725;
	}

	public Float get726() {
		return this._726;
	}

	public void set726(Float _726) {
		this._726 = _726;
	}

	public Float get727() {
		return this._727;
	}

	public void set727(Float _727) {
		this._727 = _727;
	}

	public Float get728() {
		return this._728;
	}

	public void set728(Float _728) {
		this._728 = _728;
	}

	public Set<E1> getE1s() {
		return this.e1s;
	}

	public void setE1s(Set<E1> e1s) {
		this.e1s = e1s;
	}

}
