package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * E1personDataBorneTaxpayer generated by hbm2java
 */
public class E1personDataBorneTaxpayer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idE1personDataBorneTaxpayer;
	private String name1;
	private Integer birthYear1;
	private String schoolName1;
	private String _831;
	private String name2;
	private Integer birthYear2;
	private String schoolName2;
	private String _832;
	private String name3;
	private Integer birthYear3;
	private String schoolName3;
	private String _833;
	private String name4;
	private Integer birthYear4;
	private String schoolName4;
	private String _834;
	private String fullName1;
	private String _835;
	private String relationshipWithPrincipal1;
	private String relationShipWithWife1;
	private String fullName2;
	private String _836;
	private String relationshipWithPrincipal2;
	private String relationShipWithWife2;
	private String fullName3;
	private String _837;
	private String relationshipWithPrincipal3;
	private String relationShipWithWife3;
	private String fullName4;
	private String _838;
	private String relationshipWithPrincipal4;
	private String relationShipWithWife4;
	private Set<E1> e1s = new HashSet<E1>(0);

	public E1personDataBorneTaxpayer() {
	}

	public E1personDataBorneTaxpayer(String name1, Integer birthYear1,
			String schoolName1, String _831, String name2, Integer birthYear2,
			String schoolName2, String _832, String name3, Integer birthYear3,
			String schoolName3, String _833, String name4, Integer birthYear4,
			String schoolName4, String _834, String fullName1, String _835,
			String relationshipWithPrincipal1, String relationShipWithWife1,
			String fullName2, String _836, String relationshipWithPrincipal2,
			String relationShipWithWife2, String fullName3, String _837,
			String relationshipWithPrincipal3, String relationShipWithWife3,
			String fullName4, String _838, String relationshipWithPrincipal4,
			String relationShipWithWife4, Set<E1> e1s) {
		this.name1 = name1;
		this.birthYear1 = birthYear1;
		this.schoolName1 = schoolName1;
		this._831 = _831;
		this.name2 = name2;
		this.birthYear2 = birthYear2;
		this.schoolName2 = schoolName2;
		this._832 = _832;
		this.name3 = name3;
		this.birthYear3 = birthYear3;
		this.schoolName3 = schoolName3;
		this._833 = _833;
		this.name4 = name4;
		this.birthYear4 = birthYear4;
		this.schoolName4 = schoolName4;
		this._834 = _834;
		this.fullName1 = fullName1;
		this._835 = _835;
		this.relationshipWithPrincipal1 = relationshipWithPrincipal1;
		this.relationShipWithWife1 = relationShipWithWife1;
		this.fullName2 = fullName2;
		this._836 = _836;
		this.relationshipWithPrincipal2 = relationshipWithPrincipal2;
		this.relationShipWithWife2 = relationShipWithWife2;
		this.fullName3 = fullName3;
		this._837 = _837;
		this.relationshipWithPrincipal3 = relationshipWithPrincipal3;
		this.relationShipWithWife3 = relationShipWithWife3;
		this.fullName4 = fullName4;
		this._838 = _838;
		this.relationshipWithPrincipal4 = relationshipWithPrincipal4;
		this.relationShipWithWife4 = relationShipWithWife4;
		this.e1s = e1s;
	}

	public Integer getIdE1personDataBorneTaxpayer() {
		return this.idE1personDataBorneTaxpayer;
	}

	public void setIdE1personDataBorneTaxpayer(
			Integer idE1personDataBorneTaxpayer) {
		this.idE1personDataBorneTaxpayer = idE1personDataBorneTaxpayer;
	}

	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	public Integer getBirthYear1() {
		return this.birthYear1;
	}

	public void setBirthYear1(Integer birthYear1) {
		this.birthYear1 = birthYear1;
	}

	public String getSchoolName1() {
		return this.schoolName1;
	}

	public void setSchoolName1(String schoolName1) {
		this.schoolName1 = schoolName1;
	}

	public String get831() {
		return this._831;
	}

	public void set831(String _831) {
		this._831 = _831;
	}

	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public Integer getBirthYear2() {
		return this.birthYear2;
	}

	public void setBirthYear2(Integer birthYear2) {
		this.birthYear2 = birthYear2;
	}

	public String getSchoolName2() {
		return this.schoolName2;
	}

	public void setSchoolName2(String schoolName2) {
		this.schoolName2 = schoolName2;
	}

	public String get832() {
		return this._832;
	}

	public void set832(String _832) {
		this._832 = _832;
	}

	public String getName3() {
		return this.name3;
	}

	public void setName3(String name3) {
		this.name3 = name3;
	}

	public Integer getBirthYear3() {
		return this.birthYear3;
	}

	public void setBirthYear3(Integer birthYear3) {
		this.birthYear3 = birthYear3;
	}

	public String getSchoolName3() {
		return this.schoolName3;
	}

	public void setSchoolName3(String schoolName3) {
		this.schoolName3 = schoolName3;
	}

	public String get833() {
		return this._833;
	}

	public void set833(String _833) {
		this._833 = _833;
	}

	public String getName4() {
		return this.name4;
	}

	public void setName4(String name4) {
		this.name4 = name4;
	}

	public Integer getBirthYear4() {
		return this.birthYear4;
	}

	public void setBirthYear4(Integer birthYear4) {
		this.birthYear4 = birthYear4;
	}

	public String getSchoolName4() {
		return this.schoolName4;
	}

	public void setSchoolName4(String schoolName4) {
		this.schoolName4 = schoolName4;
	}

	public String get834() {
		return this._834;
	}

	public void set834(String _834) {
		this._834 = _834;
	}

	public String getFullName1() {
		return this.fullName1;
	}

	public void setFullName1(String fullName1) {
		this.fullName1 = fullName1;
	}

	public String get835() {
		return this._835;
	}

	public void set835(String _835) {
		this._835 = _835;
	}

	public String getRelationshipWithPrincipal1() {
		return this.relationshipWithPrincipal1;
	}

	public void setRelationshipWithPrincipal1(String relationshipWithPrincipal1) {
		this.relationshipWithPrincipal1 = relationshipWithPrincipal1;
	}

	public String getRelationShipWithWife1() {
		return this.relationShipWithWife1;
	}

	public void setRelationShipWithWife1(String relationShipWithWife1) {
		this.relationShipWithWife1 = relationShipWithWife1;
	}

	public String getFullName2() {
		return this.fullName2;
	}

	public void setFullName2(String fullName2) {
		this.fullName2 = fullName2;
	}

	public String get836() {
		return this._836;
	}

	public void set836(String _836) {
		this._836 = _836;
	}

	public String getRelationshipWithPrincipal2() {
		return this.relationshipWithPrincipal2;
	}

	public void setRelationshipWithPrincipal2(String relationshipWithPrincipal2) {
		this.relationshipWithPrincipal2 = relationshipWithPrincipal2;
	}

	public String getRelationShipWithWife2() {
		return this.relationShipWithWife2;
	}

	public void setRelationShipWithWife2(String relationShipWithWife2) {
		this.relationShipWithWife2 = relationShipWithWife2;
	}

	public String getFullName3() {
		return this.fullName3;
	}

	public void setFullName3(String fullName3) {
		this.fullName3 = fullName3;
	}

	public String get837() {
		return this._837;
	}

	public void set837(String _837) {
		this._837 = _837;
	}

	public String getRelationshipWithPrincipal3() {
		return this.relationshipWithPrincipal3;
	}

	public void setRelationshipWithPrincipal3(String relationshipWithPrincipal3) {
		this.relationshipWithPrincipal3 = relationshipWithPrincipal3;
	}

	public String getRelationShipWithWife3() {
		return this.relationShipWithWife3;
	}

	public void setRelationShipWithWife3(String relationShipWithWife3) {
		this.relationShipWithWife3 = relationShipWithWife3;
	}

	public String getFullName4() {
		return this.fullName4;
	}

	public void setFullName4(String fullName4) {
		this.fullName4 = fullName4;
	}

	public String get838() {
		return this._838;
	}

	public void set838(String _838) {
		this._838 = _838;
	}

	public String getRelationshipWithPrincipal4() {
		return this.relationshipWithPrincipal4;
	}

	public void setRelationshipWithPrincipal4(String relationshipWithPrincipal4) {
		this.relationshipWithPrincipal4 = relationshipWithPrincipal4;
	}

	public String getRelationShipWithWife4() {
		return this.relationShipWithWife4;
	}

	public void setRelationShipWithWife4(String relationShipWithWife4) {
		this.relationShipWithWife4 = relationShipWithWife4;
	}

	public Set<E1> getE1s() {
		return this.e1s;
	}

	public void setE1s(Set<E1> e1s) {
		this.e1s = e1s;
	}

}
