package gr.manousos.model;

// Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1

/**
 * E1personDataBorneTaxpayer generated by hbm2java
 */
public class E1personDataBorneTaxpayer implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private E1Id id;
    private E1 e1;
    private String name1;
    private Integer birthYear1;
    private String schoolName1;
    private String _831;
    private String name2;
    private Integer birthYear2;
    private String schoolName2;
    private String _832;
    private String name3;
    private Integer birthYear3;
    private String schoolName3;
    private String _833;
    private String name4;
    private Integer birthYear4;
    private String schoolName4;
    private String _834;
    private String fullName1;
    private String _835;
    private String relationshipWithPrincipal1;
    private String relationShipWithWife1;
    private String fullName2;
    private String _836;
    private String relationshipWithPrincipal2;
    private String relationShipWithWife2;
    private String fullName3;
    private String _837;
    private String relationshipWithPrincipal3;
    private String relationShipWithWife3;
    private String fullName4;
    private String _838;
    private String relationshipWithPrincipal4;
    private String relationShipWithWife4;

    public E1personDataBorneTaxpayer() {
    }

    public E1personDataBorneTaxpayer(E1 e1) {
	this.e1 = e1;
    }

    public E1personDataBorneTaxpayer(E1 e1, String name1, Integer birthYear1,
	    String schoolName1, String _831, String name2, Integer birthYear2,
	    String schoolName2, String _832, String name3, Integer birthYear3,
	    String schoolName3, String _833, String name4, Integer birthYear4,
	    String schoolName4, String _834, String fullName1, String _835,
	    String relationshipWithPrincipal1, String relationShipWithWife1,
	    String fullName2, String _836, String relationshipWithPrincipal2,
	    String relationShipWithWife2, String fullName3, String _837,
	    String relationshipWithPrincipal3, String relationShipWithWife3,
	    String fullName4, String _838, String relationshipWithPrincipal4,
	    String relationShipWithWife4) {
	this.e1 = e1;
	this.name1 = name1;
	this.birthYear1 = birthYear1;
	this.schoolName1 = schoolName1;
	this._831 = _831;
	this.name2 = name2;
	this.birthYear2 = birthYear2;
	this.schoolName2 = schoolName2;
	this._832 = _832;
	this.name3 = name3;
	this.birthYear3 = birthYear3;
	this.schoolName3 = schoolName3;
	this._833 = _833;
	this.name4 = name4;
	this.birthYear4 = birthYear4;
	this.schoolName4 = schoolName4;
	this._834 = _834;
	this.fullName1 = fullName1;
	this._835 = _835;
	this.relationshipWithPrincipal1 = relationshipWithPrincipal1;
	this.relationShipWithWife1 = relationShipWithWife1;
	this.fullName2 = fullName2;
	this._836 = _836;
	this.relationshipWithPrincipal2 = relationshipWithPrincipal2;
	this.relationShipWithWife2 = relationShipWithWife2;
	this.fullName3 = fullName3;
	this._837 = _837;
	this.relationshipWithPrincipal3 = relationshipWithPrincipal3;
	this.relationShipWithWife3 = relationShipWithWife3;
	this.fullName4 = fullName4;
	this._838 = _838;
	this.relationshipWithPrincipal4 = relationshipWithPrincipal4;
	this.relationShipWithWife4 = relationShipWithWife4;
    }

    public E1Id getId() {
	return this.id;
    }

    public void setId(E1Id id) {
	this.id = id;
    }

    public E1 getE1() {
	return this.e1;
    }

    public void setE1(E1 e1) {
	this.e1 = e1;
    }

    public String getName1() {
	return name1;
    }

    public void setName1(String name1) {
	this.name1 = name1;
    }

    public Integer getBirthYear1() {
	return birthYear1;
    }

    public void setBirthYear1(Integer birthYear1) {
	this.birthYear1 = birthYear1;
    }

    public String getSchoolName1() {
	return schoolName1;
    }

    public void setSchoolName1(String schoolName1) {
	this.schoolName1 = schoolName1;
    }

    public String get_831() {
	return _831;
    }

    public void set_831(String _831) {
	this._831 = _831;
    }

    public String getName2() {
	return name2;
    }

    public void setName2(String name2) {
	this.name2 = name2;
    }

    public Integer getBirthYear2() {
	return birthYear2;
    }

    public void setBirthYear2(Integer birthYear2) {
	this.birthYear2 = birthYear2;
    }

    public String getSchoolName2() {
	return schoolName2;
    }

    public void setSchoolName2(String schoolName2) {
	this.schoolName2 = schoolName2;
    }

    public String get_832() {
	return _832;
    }

    public void set_832(String _832) {
	this._832 = _832;
    }

    public String getName3() {
	return name3;
    }

    public void setName3(String name3) {
	this.name3 = name3;
    }

    public Integer getBirthYear3() {
	return birthYear3;
    }

    public void setBirthYear3(Integer birthYear3) {
	this.birthYear3 = birthYear3;
    }

    public String getSchoolName3() {
	return schoolName3;
    }

    public void setSchoolName3(String schoolName3) {
	this.schoolName3 = schoolName3;
    }

    public String get_833() {
	return _833;
    }

    public void set_833(String _833) {
	this._833 = _833;
    }

    public String getName4() {
	return name4;
    }

    public void setName4(String name4) {
	this.name4 = name4;
    }

    public Integer getBirthYear4() {
	return birthYear4;
    }

    public void setBirthYear4(Integer birthYear4) {
	this.birthYear4 = birthYear4;
    }

    public String getSchoolName4() {
	return schoolName4;
    }

    public void setSchoolName4(String schoolName4) {
	this.schoolName4 = schoolName4;
    }

    public String get_834() {
	return _834;
    }

    public void set_834(String _834) {
	this._834 = _834;
    }

    public String getFullName1() {
	return fullName1;
    }

    public void setFullName1(String fullName1) {
	this.fullName1 = fullName1;
    }

    public String get_835() {
	return _835;
    }

    public void set_835(String _835) {
	this._835 = _835;
    }

    public String getRelationshipWithPrincipal1() {
	return relationshipWithPrincipal1;
    }

    public void setRelationshipWithPrincipal1(String relationshipWithPrincipal1) {
	this.relationshipWithPrincipal1 = relationshipWithPrincipal1;
    }

    public String getRelationShipWithWife1() {
	return relationShipWithWife1;
    }

    public void setRelationShipWithWife1(String relationShipWithWife1) {
	this.relationShipWithWife1 = relationShipWithWife1;
    }

    public String getFullName2() {
	return fullName2;
    }

    public void setFullName2(String fullName2) {
	this.fullName2 = fullName2;
    }

    public String get_836() {
	return _836;
    }

    public void set_836(String _836) {
	this._836 = _836;
    }

    public String getRelationshipWithPrincipal2() {
	return relationshipWithPrincipal2;
    }

    public void setRelationshipWithPrincipal2(String relationshipWithPrincipal2) {
	this.relationshipWithPrincipal2 = relationshipWithPrincipal2;
    }

    public String getRelationShipWithWife2() {
	return relationShipWithWife2;
    }

    public void setRelationShipWithWife2(String relationShipWithWife2) {
	this.relationShipWithWife2 = relationShipWithWife2;
    }

    public String getFullName3() {
	return fullName3;
    }

    public void setFullName3(String fullName3) {
	this.fullName3 = fullName3;
    }

    public String get_837() {
	return _837;
    }

    public void set_837(String _837) {
	this._837 = _837;
    }

    public String getRelationshipWithPrincipal3() {
	return relationshipWithPrincipal3;
    }

    public void setRelationshipWithPrincipal3(String relationshipWithPrincipal3) {
	this.relationshipWithPrincipal3 = relationshipWithPrincipal3;
    }

    public String getRelationShipWithWife3() {
	return relationShipWithWife3;
    }

    public void setRelationShipWithWife3(String relationShipWithWife3) {
	this.relationShipWithWife3 = relationShipWithWife3;
    }

    public String getFullName4() {
	return fullName4;
    }

    public void setFullName4(String fullName4) {
	this.fullName4 = fullName4;
    }

    public String get_838() {
	return _838;
    }

    public void set_838(String _838) {
	this._838 = _838;
    }

    public String getRelationshipWithPrincipal4() {
	return relationshipWithPrincipal4;
    }

    public void setRelationshipWithPrincipal4(String relationshipWithPrincipal4) {
	this.relationshipWithPrincipal4 = relationshipWithPrincipal4;
    }

    public String getRelationShipWithWife4() {
	return relationShipWithWife4;
    }

    public void setRelationShipWithWife4(String relationShipWithWife4) {
	this.relationShipWithWife4 = relationShipWithWife4;
    }

}
