package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1prepaidTaxes generated by hbm2java
 */
@XmlRootElement
public class E1prepaidTaxes implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer idE1prepaidTaxes;
    private Float _601;
    private Float _602;
    private Float _603;
    private Float _604;
    private Float _605;
    private Float _606;
    private Float _607;
    private Float _608;
    private Float _609;
    private Float _610;
    private Float _651;
    private Float _652;
    private Float _293;
    private Float _294;
    private Float _313;
    private Float _314;
    private Float _315;
    private Float _316;
    private Float _297;
    private Float _298;
    private Float _127;
    private String _128;
    private Set<E1> e1s = new HashSet<E1>(0);

    public E1prepaidTaxes() {
    }

    public E1prepaidTaxes(Float _601, Float _602, Float _603, Float _604,
	    Float _605, Float _606, Float _607, Float _608, Float _609,
	    Float _610, Float _651, Float _652, Float _293, Float _294,
	    Float _313, Float _314, Float _315, Float _316, Float _297,
	    Float _298, Float _127, String _128, Set<E1> e1s) {
	this._601 = _601;
	this._602 = _602;
	this._603 = _603;
	this._604 = _604;
	this._605 = _605;
	this._606 = _606;
	this._607 = _607;
	this._608 = _608;
	this._609 = _609;
	this._610 = _610;
	this._651 = _651;
	this._652 = _652;
	this._293 = _293;
	this._294 = _294;
	this._313 = _313;
	this._314 = _314;
	this._315 = _315;
	this._316 = _316;
	this._297 = _297;
	this._298 = _298;
	this._127 = _127;
	this._128 = _128;
	this.e1s = e1s;
    }

    public Integer getIdE1prepaidTaxes() {
	return idE1prepaidTaxes;
    }

    public void setIdE1prepaidTaxes(Integer idE1prepaidTaxes) {
	this.idE1prepaidTaxes = idE1prepaidTaxes;
    }

    public Float get_601() {
	return _601;
    }

    public void set_601(Float _601) {
	this._601 = _601;
    }

    public Float get_602() {
	return _602;
    }

    public void set_602(Float _602) {
	this._602 = _602;
    }

    public Float get_603() {
	return _603;
    }

    public void set_603(Float _603) {
	this._603 = _603;
    }

    public Float get_604() {
	return _604;
    }

    public void set_604(Float _604) {
	this._604 = _604;
    }

    public Float get_605() {
	return _605;
    }

    public void set_605(Float _605) {
	this._605 = _605;
    }

    public Float get_606() {
	return _606;
    }

    public void set_606(Float _606) {
	this._606 = _606;
    }

    public Float get_607() {
	return _607;
    }

    public void set_607(Float _607) {
	this._607 = _607;
    }

    public Float get_608() {
	return _608;
    }

    public void set_608(Float _608) {
	this._608 = _608;
    }

    public Float get_609() {
	return _609;
    }

    public void set_609(Float _609) {
	this._609 = _609;
    }

    public Float get_610() {
	return _610;
    }

    public void set_610(Float _610) {
	this._610 = _610;
    }

    public Float get_651() {
	return _651;
    }

    public void set_651(Float _651) {
	this._651 = _651;
    }

    public Float get_652() {
	return _652;
    }

    public void set_652(Float _652) {
	this._652 = _652;
    }

    public Float get_293() {
	return _293;
    }

    public void set_293(Float _293) {
	this._293 = _293;
    }

    public Float get_294() {
	return _294;
    }

    public void set_294(Float _294) {
	this._294 = _294;
    }

    public Float get_313() {
	return _313;
    }

    public void set_313(Float _313) {
	this._313 = _313;
    }

    public Float get_314() {
	return _314;
    }

    public void set_314(Float _314) {
	this._314 = _314;
    }

    public Float get_315() {
	return _315;
    }

    public void set_315(Float _315) {
	this._315 = _315;
    }

    public Float get_316() {
	return _316;
    }

    public void set_316(Float _316) {
	this._316 = _316;
    }

    public Float get_297() {
	return _297;
    }

    public void set_297(Float _297) {
	this._297 = _297;
    }

    public Float get_298() {
	return _298;
    }

    public void set_298(Float _298) {
	this._298 = _298;
    }

    public Float get_127() {
	return _127;
    }

    public void set_127(Float _127) {
	this._127 = _127;
    }

    public String get_128() {
	return _128;
    }

    public void set_128(String _128) {
	this._128 = _128;
    }

    public Set<E1> getE1s() {
	return this.e1s;
    }

    public void setE1s(Set<E1> e1s) {
	this.e1s = e1s;
    }

}
