package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1prepaidTaxes generated by hbm2java
 */
@XmlRootElement
public class E1prepaidTaxes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idE1prepaidTaxes;
	private Float _601;
	private Float _602;
	private Float _603;
	private Float _604;
	private Float _605;
	private Float _606;
	private Float _607;
	private Float _608;
	private Float _609;
	private Float _610;
	private Float _651;
	private Float _652;
	private Float _293;
	private Float _294;
	private Float _313;
	private Float _314;
	private Float _315;
	private Float _316;
	private Float _297;
	private Float _298;
	private Float _127;
	private String _128;
	private Set<E1> e1s = new HashSet<E1>(0);

	public E1prepaidTaxes() {
	}

	public E1prepaidTaxes(Float _601, Float _602, Float _603, Float _604,
			Float _605, Float _606, Float _607, Float _608, Float _609,
			Float _610, Float _651, Float _652, Float _293, Float _294,
			Float _313, Float _314, Float _315, Float _316, Float _297,
			Float _298, Float _127, String _128, Set<E1> e1s) {
		this._601 = _601;
		this._602 = _602;
		this._603 = _603;
		this._604 = _604;
		this._605 = _605;
		this._606 = _606;
		this._607 = _607;
		this._608 = _608;
		this._609 = _609;
		this._610 = _610;
		this._651 = _651;
		this._652 = _652;
		this._293 = _293;
		this._294 = _294;
		this._313 = _313;
		this._314 = _314;
		this._315 = _315;
		this._316 = _316;
		this._297 = _297;
		this._298 = _298;
		this._127 = _127;
		this._128 = _128;
		this.e1s = e1s;
	}

	public Integer getIdE1prepaidTaxes() {
		return this.idE1prepaidTaxes;
	}

	public void setIdE1prepaidTaxes(Integer idE1prepaidTaxes) {
		this.idE1prepaidTaxes = idE1prepaidTaxes;
	}

	public Float get601() {
		return this._601;
	}

	public void set601(Float _601) {
		this._601 = _601;
	}

	public Float get602() {
		return this._602;
	}

	public void set602(Float _602) {
		this._602 = _602;
	}

	public Float get603() {
		return this._603;
	}

	public void set603(Float _603) {
		this._603 = _603;
	}

	public Float get604() {
		return this._604;
	}

	public void set604(Float _604) {
		this._604 = _604;
	}

	public Float get605() {
		return this._605;
	}

	public void set605(Float _605) {
		this._605 = _605;
	}

	public Float get606() {
		return this._606;
	}

	public void set606(Float _606) {
		this._606 = _606;
	}

	public Float get607() {
		return this._607;
	}

	public void set607(Float _607) {
		this._607 = _607;
	}

	public Float get608() {
		return this._608;
	}

	public void set608(Float _608) {
		this._608 = _608;
	}

	public Float get609() {
		return this._609;
	}

	public void set609(Float _609) {
		this._609 = _609;
	}

	public Float _get610() {
		return this._610;
	}

	public void set610(Float _610) {
		this._610 = _610;
	}

	public Float _get651() {
		return this._651;
	}

	public void set651(Float _651) {
		this._651 = _651;
	}

	public Float _get652() {
		return this._652;
	}

	public void set652(Float _652) {
		this._652 = _652;
	}

	public Float _get293() {
		return this._293;
	}

	public void set293(Float _293) {
		this._293 = _293;
	}

	public Float _get294() {
		return this._294;
	}

	public void set294(Float _294) {
		this._294 = _294;
	}

	public Float _get313() {
		return this._313;
	}

	public void set313(Float _313) {
		this._313 = _313;
	}

	public Float _get314() {
		return this._314;
	}

	public void set314(Float _314) {
		this._314 = _314;
	}

	public Float _get315() {
		return this._315;
	}

	public void set315(Float _315) {
		this._315 = _315;
	}

	public Float _get316() {
		return this._316;
	}

	public void set316(Float _316) {
		this._316 = _316;
	}

	public Float _get297() {
		return this._297;
	}

	public void set297(Float _297) {
		this._297 = _297;
	}

	public Float _get298() {
		return this._298;
	}

	public void set298(Float _298) {
		this._298 = _298;
	}

	public Float _get127() {
		return this._127;
	}

	public void set127(Float _127) {
		this._127 = _127;
	}

	public String get128() {
		return this._128;
	}

	public void set128(String _128) {
		this._128 = _128;
	}

	public Set<E1> getE1s() {
		return this.e1s;
	}

	public void setE1s(Set<E1> e1s) {
		this.e1s = e1s;
	}

}
