package gr.manousos.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

/**
 * E1relatePersons generated by hbm2java
 */
@XmlRootElement
public class E1relatePersons implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private E1relatePersonsId id;

	public E1relatePersons() {
	}

	public E1relatePersons(E1relatePersonsId id) {
		this.id = id;
	}

	public E1relatePersonsId getId() {
		return this.id;
	}

	public void setId(E1relatePersonsId id) {
		this.id = id;
	}

}
