package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1reduceTax generated by hbm2java
 */
@XmlRootElement
public class E1reduceTax implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idE1reduceTax;
	private Integer _001;
	private Integer _002;
	private Integer _003;
	private Integer _004;
	private Integer _005;
	private Integer _006;
	private Set<E1> e1s = new HashSet<E1>(0);

	public E1reduceTax() {
	}

	public E1reduceTax(Integer _001, Integer _002, Integer _003, Integer _004,
			Integer _005, Integer _006, Set<E1> e1s) {
		this._001 = _001;
		this._002 = _002;
		this._003 = _003;
		this._004 = _004;
		this._005 = _005;
		this._006 = _006;
		this.e1s = e1s;
	}

	public Integer getIdE1reduceTax() {
		return this.idE1reduceTax;
	}

	public void setIdE1reduceTax(Integer idE1reduceTax) {
		this.idE1reduceTax = idE1reduceTax;
	}

	public Integer get_001() {
		return this._001;
	}

	public void set001(Integer _001) {
		this._001 = _001;
	}

	public Integer get_002() {
	    return _002;
	}

	public void set_002(Integer _002) {
	    this._002 = _002;
	}

	public Integer get_003() {
	    return _003;
	}

	public void set_003(Integer _003) {
	    this._003 = _003;
	}

	public Integer get_004() {
	    return _004;
	}

	public void set_004(Integer _004) {
	    this._004 = _004;
	}

	public Integer get_005() {
	    return _005;
	}

	public void set_005(Integer _005) {
	    this._005 = _005;
	}

	public Integer get_006() {
	    return _006;
	}

	public void set_006(Integer _006) {
	    this._006 = _006;
	}

	public void set_001(Integer _001) {
	    this._001 = _001;
	}
	
	public Set<E1> getE1s() {
		return this.e1s;
	}

	public void setE1s(Set<E1> e1s) {
		this.e1s = e1s;
	}

}
