package gr.manousos.model;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1taxableIncomes generated by hbm2java
 */
@XmlRootElement
public class E1taxableIncomes implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer e1taxableIncome;
    private Float _301;
    private Float _302;
    private Float _303;
    private Float _304;
    private Float _321;
    private Float _322;
    private Float _317;
    private Float _318;
    private Float _461;
    private Float _462;
    private Float _921;
    private Float _922;
    private Float _919;
    private Float _920;
    private Float _915;
    private Float _916;
    private Float _923;
    private Float _924;
    private Float _335;
    private Float _336;
    private Float _326;
    private Float _337;
    private Float _338;
    private Float _339;
    private Float _340;
    private Float _465;
    private Float _466;
    private Float _467;
    private Float _468;
    private Float _475;
    private Float _476;
    private Float _479;
    private Float _480;
    private Float _481;
    private Float _482;
    private Float _401;
    private Float _402;
    private Float _403;
    private Float _404;
    private Float _405;
    private Float _406;
    private Float _407;
    private Float _408;
    private Float _413;
    private Float _414;
    private Float _415;
    private Float _416;
    private Float _425;
    private Float _426;
    private Float _501;
    private Float _502;
    private Float _503;
    private Float _504;
    private Float _505;
    private Float _506;
    private Float _507;
    private Float _508;
    private Float _511;
    private Float _512;
    private Float _515;
    private Float _516;
    private Float _517;
    private Float _518;
    private Float _103;
    private Float _104;
    private Float _121;
    private Float _122;
    private Float _105;
    private Float _106;
    private Float _107;
    private Float _108;
    private Float _109;
    private Float _110;
    private Float _101;
    private Float _102;
    private Float _909;
    private Float _910;
    private Float _111;
    private Float _112;
    private Float _113;
    private Float _114;
    private Float _129;
    private Float _130;
    private Float _143;
    private Float _144;
    private Float _145;
    private Float _146;
    private Float _147;
    private Float _148;
    private Float _141;
    private Float _142;
    private Float _701;
    private Float _702;
    private Float _123;
    private Float _124;
    private Float _125;
    private Float _126;
    private Float _151;
    private Float _152;
    private Float _163;
    private Float _164;
    private Float _165;
    private Float _166;
    private Float _159;
    private Float _160;
    private Float _175;
    private Float _176;
    private Float _131;
    private Float _132;
    private Float _133;
    private Float _134;
    private Float _741;
    private Float _742;
    private Float _291;
    private Float _292;
    private Float _389;
    private Float _390;
    private Float _391;
    private Float _392;
    private Float _463;
    private Float _464;
    private Float _471;
    private Float _472;
    private Float _411;
    private Float _412;
    private Float _421;
    private Float _422;
    private Float _509;
    private Float _510;
    private Float _513;
    private Float _514;
    private Float _295;
    private Float _296;
    private Float _171;
    private Float _172;
    private Float _173;
    private Float _174;
    private Float _395;
    private Float _396;
    private String agrLocation1;
    private String agrProdKind1;
    private Float agrPopulation1;
    private Integer agrLocationType1;
    private Integer agrHasWater1;
    private Float agrNetIncome1;
    private Float agrTotalNetincome1;
    private Float agrTotalWifeNetincome1;
    private String agrLocation2;
    private String agrProdKind2;
    private Float agrPopulation2;
    private Integer agrLocationType2;
    private Integer agrHasWater2;
    private Float agrNetIncome2;
    private Float agrTotalNetincome2;
    private Float agrTotalWifeNetincome2;
    private String agrLocation3;
    private String agrProdKind3;
    private Float agrPopulation3;
    private Integer agrLocationType3;
    private Integer agrHasWater3;
    private Float agrNetIncome3;
    private Float agrTotalNetincome3;
    private Float agrTotalWifeNetincome3;
    private String agrLocation4;
    private String agrProdKind4;
    private Float agrPopulation4;
    private Integer agrLocationType4;
    private Integer agrHasWater4;
    private Float agrNetIncome4;
    private Float agrTotalNetincome4;
    private Float agrTotalWifeNetincome4;
    private Set<E1> e1s = new HashSet<E1>(0);

    public E1taxableIncomes() {
    }

    public E1taxableIncomes(Float _301, Float _302, Float _303, Float _304,
	    Float _321, Float _322, Float _317, Float _318, Float _461,
	    Float _462, Float _921, Float _922, Float _919, Float _920,
	    Float _915, Float _916, Float _923, Float _924, Float _335,
	    Float _336, Float _326, Float _337, Float _338, Float _339,
	    Float _340, Float _465, Float _466, Float _467, Float _468,
	    Float _475, Float _476, Float _479, Float _480, Float _481,
	    Float _482, Float _401, Float _402, Float _403, Float _404,
	    Float _405, Float _406, Float _407, Float _408, Float _413,
	    Float _414, Float _415, Float _416, Float _425, Float _426,
	    Float _501, Float _502, Float _503, Float _504, Float _505,
	    Float _506, Float _507, Float _508, Float _511, Float _512,
	    Float _515, Float _516, Float _517, Float _518, Float _103,
	    Float _104, Float _121, Float _122, Float _105, Float _106,
	    Float _107, Float _108, Float _109, Float _110, Float _101,
	    Float _102, Float _909, Float _910, Float _111, Float _112,
	    Float _113, Float _114, Float _129, Float _130, Float _143,
	    Float _144, Float _145, Float _146, Float _147, Float _148,
	    Float _141, Float _142, Float _701, Float _702, Float _123,
	    Float _124, Float _125, Float _126, Float _151, Float _152,
	    Float _163, Float _164, Float _165, Float _166, Float _159,
	    Float _160, Float _175, Float _176, Float _131, Float _132,
	    Float _133, Float _134, Float _741, Float _742, Float _291,
	    Float _292, Float _389, Float _390, Float _391, Float _392,
	    Float _463, Float _464, Float _471, Float _472, Float _411,
	    Float _412, Float _421, Float _422, Float _509, Float _510,
	    Float _513, Float _514, Float _295, Float _296, Float _171,
	    Float _172, Float _173, Float _174, Float _395, Float _396,
	    String agrLocation1, String agrProdKind1, Float agrPopulation1,
	    Integer agrLocationType1, Integer agrHasWater1,
	    Float agrNetIncome1, Float agrTotalNetincome1,
	    Float agrTotalWifeNetincome1, String agrLocation2,
	    String agrProdKind2, Float agrPopulation2,
	    Integer agrLocationType2, Integer agrHasWater2,
	    Float agrNetIncome2, Float agrTotalNetincome2,
	    Float agrTotalWifeNetincome2, String agrLocation3,
	    String agrProdKind3, Float agrPopulation3,
	    Integer agrLocationType3, Integer agrHasWater3,
	    Float agrNetIncome3, Float agrTotalNetincome3,
	    Float agrTotalWifeNetincome3, String agrLocation4,
	    String agrProdKind4, Float agrPopulation4,
	    Integer agrLocationType4, Integer agrHasWater4,
	    Float agrNetIncome4, Float agrTotalNetincome4,
	    Float agrTotalWifeNetincome4, Set<E1> e1s) {
	this._301 = _301;
	this._302 = _302;
	this._303 = _303;
	this._304 = _304;
	this._321 = _321;
	this._322 = _322;
	this._317 = _317;
	this._318 = _318;
	this._461 = _461;
	this._462 = _462;
	this._921 = _921;
	this._922 = _922;
	this._919 = _919;
	this._920 = _920;
	this._915 = _915;
	this._916 = _916;
	this._923 = _923;
	this._924 = _924;
	this._335 = _335;
	this._336 = _336;
	this._326 = _326;
	this._337 = _337;
	this._338 = _338;
	this._339 = _339;
	this._340 = _340;
	this._465 = _465;
	this._466 = _466;
	this._467 = _467;
	this._468 = _468;
	this._475 = _475;
	this._476 = _476;
	this._479 = _479;
	this._480 = _480;
	this._481 = _481;
	this._482 = _482;
	this._401 = _401;
	this._402 = _402;
	this._403 = _403;
	this._404 = _404;
	this._405 = _405;
	this._406 = _406;
	this._407 = _407;
	this._408 = _408;
	this._413 = _413;
	this._414 = _414;
	this._415 = _415;
	this._416 = _416;
	this._425 = _425;
	this._426 = _426;
	this._501 = _501;
	this._502 = _502;
	this._503 = _503;
	this._504 = _504;
	this._505 = _505;
	this._506 = _506;
	this._507 = _507;
	this._508 = _508;
	this._511 = _511;
	this._512 = _512;
	this._515 = _515;
	this._516 = _516;
	this._517 = _517;
	this._518 = _518;
	this._103 = _103;
	this._104 = _104;
	this._121 = _121;
	this._122 = _122;
	this._105 = _105;
	this._106 = _106;
	this._107 = _107;
	this._108 = _108;
	this._109 = _109;
	this._110 = _110;
	this._101 = _101;
	this._102 = _102;
	this._909 = _909;
	this._910 = _910;
	this._111 = _111;
	this._112 = _112;
	this._113 = _113;
	this._114 = _114;
	this._129 = _129;
	this._130 = _130;
	this._143 = _143;
	this._144 = _144;
	this._145 = _145;
	this._146 = _146;
	this._147 = _147;
	this._148 = _148;
	this._141 = _141;
	this._142 = _142;
	this._701 = _701;
	this._702 = _702;
	this._123 = _123;
	this._124 = _124;
	this._125 = _125;
	this._126 = _126;
	this._151 = _151;
	this._152 = _152;
	this._163 = _163;
	this._164 = _164;
	this._165 = _165;
	this._166 = _166;
	this._159 = _159;
	this._160 = _160;
	this._175 = _175;
	this._176 = _176;
	this._131 = _131;
	this._132 = _132;
	this._133 = _133;
	this._134 = _134;
	this._741 = _741;
	this._742 = _742;
	this._291 = _291;
	this._292 = _292;
	this._389 = _389;
	this._390 = _390;
	this._391 = _391;
	this._392 = _392;
	this._463 = _463;
	this._464 = _464;
	this._471 = _471;
	this._472 = _472;
	this._411 = _411;
	this._412 = _412;
	this._421 = _421;
	this._422 = _422;
	this._509 = _509;
	this._510 = _510;
	this._513 = _513;
	this._514 = _514;
	this._295 = _295;
	this._296 = _296;
	this._171 = _171;
	this._172 = _172;
	this._173 = _173;
	this._174 = _174;
	this._395 = _395;
	this._396 = _396;
	this.agrLocation1 = agrLocation1;
	this.agrProdKind1 = agrProdKind1;
	this.agrPopulation1 = agrPopulation1;
	this.agrLocationType1 = agrLocationType1;
	this.agrHasWater1 = agrHasWater1;
	this.agrNetIncome1 = agrNetIncome1;
	this.agrTotalNetincome1 = agrTotalNetincome1;
	this.agrTotalWifeNetincome1 = agrTotalWifeNetincome1;
	this.agrLocation2 = agrLocation2;
	this.agrProdKind2 = agrProdKind2;
	this.agrPopulation2 = agrPopulation2;
	this.agrLocationType2 = agrLocationType2;
	this.agrHasWater2 = agrHasWater2;
	this.agrNetIncome2 = agrNetIncome2;
	this.agrTotalNetincome2 = agrTotalNetincome2;
	this.agrTotalWifeNetincome2 = agrTotalWifeNetincome2;
	this.agrLocation3 = agrLocation3;
	this.agrProdKind3 = agrProdKind3;
	this.agrPopulation3 = agrPopulation3;
	this.agrLocationType3 = agrLocationType3;
	this.agrHasWater3 = agrHasWater3;
	this.agrNetIncome3 = agrNetIncome3;
	this.agrTotalNetincome3 = agrTotalNetincome3;
	this.agrTotalWifeNetincome3 = agrTotalWifeNetincome3;
	this.agrLocation4 = agrLocation4;
	this.agrProdKind4 = agrProdKind4;
	this.agrPopulation4 = agrPopulation4;
	this.agrLocationType4 = agrLocationType4;
	this.agrHasWater4 = agrHasWater4;
	this.agrNetIncome4 = agrNetIncome4;
	this.agrTotalNetincome4 = agrTotalNetincome4;
	this.agrTotalWifeNetincome4 = agrTotalWifeNetincome4;
	this.e1s = e1s;
    }

    public Integer getE1taxableIncome() {
	return this.e1taxableIncome;
    }

    public void setE1taxableIncome(Integer e1taxableIncome) {
	this.e1taxableIncome = e1taxableIncome;
    }

    public Float get_301() {
	return _301;
    }

    public void set_301(Float _301) {
	this._301 = _301;
    }

    public Float get_302() {
	return _302;
    }

    public void set_302(Float _302) {
	this._302 = _302;
    }

    public Float get_303() {
	return _303;
    }

    public void set_303(Float _303) {
	this._303 = _303;
    }

    public Float get_304() {
	return _304;
    }

    public void set_304(Float _304) {
	this._304 = _304;
    }

    public Float get_321() {
	return _321;
    }

    public void set_321(Float _321) {
	this._321 = _321;
    }

    public Float get_322() {
	return _322;
    }

    public void set_322(Float _322) {
	this._322 = _322;
    }

    public Float get_317() {
	return _317;
    }

    public void set_317(Float _317) {
	this._317 = _317;
    }

    public Float get_318() {
	return _318;
    }

    public void set_318(Float _318) {
	this._318 = _318;
    }

    public Float get_461() {
	return _461;
    }

    public void set_461(Float _461) {
	this._461 = _461;
    }

    public Float get_462() {
	return _462;
    }

    public void set_462(Float _462) {
	this._462 = _462;
    }

    public Float get_921() {
	return _921;
    }

    public void set_921(Float _921) {
	this._921 = _921;
    }

    public Float get_922() {
	return _922;
    }

    public void set_922(Float _922) {
	this._922 = _922;
    }

    public Float get_919() {
	return _919;
    }

    public void set_919(Float _919) {
	this._919 = _919;
    }

    public Float get_920() {
	return _920;
    }

    public void set_920(Float _920) {
	this._920 = _920;
    }

    public Float get_915() {
	return _915;
    }

    public void set_915(Float _915) {
	this._915 = _915;
    }

    public Float get_916() {
	return _916;
    }

    public void set_916(Float _916) {
	this._916 = _916;
    }

    public Float get_923() {
	return _923;
    }

    public void set_923(Float _923) {
	this._923 = _923;
    }

    public Float get_924() {
	return _924;
    }

    public void set_924(Float _924) {
	this._924 = _924;
    }

    public Float get_335() {
	return _335;
    }

    public void set_335(Float _335) {
	this._335 = _335;
    }

    public Float get_336() {
	return _336;
    }

    public void set_336(Float _336) {
	this._336 = _336;
    }

    public Float get_326() {
	return _326;
    }

    public void set_326(Float _326) {
	this._326 = _326;
    }

    public Float get_337() {
	return _337;
    }

    public void set_337(Float _337) {
	this._337 = _337;
    }

    public Float get_338() {
	return _338;
    }

    public void set_338(Float _338) {
	this._338 = _338;
    }

    public Float get_339() {
	return _339;
    }

    public void set_339(Float _339) {
	this._339 = _339;
    }

    public Float get_340() {
	return _340;
    }

    public void set_340(Float _340) {
	this._340 = _340;
    }

    public Float get_465() {
	return _465;
    }

    public void set_465(Float _465) {
	this._465 = _465;
    }

    public Float get_466() {
	return _466;
    }

    public void set_466(Float _466) {
	this._466 = _466;
    }

    public Float get_467() {
	return _467;
    }

    public void set_467(Float _467) {
	this._467 = _467;
    }

    public Float get_468() {
	return _468;
    }

    public void set_468(Float _468) {
	this._468 = _468;
    }

    public Float get_475() {
	return _475;
    }

    public void set_475(Float _475) {
	this._475 = _475;
    }

    public Float get_476() {
	return _476;
    }

    public void set_476(Float _476) {
	this._476 = _476;
    }

    public Float get_479() {
	return _479;
    }

    public void set_479(Float _479) {
	this._479 = _479;
    }

    public Float get_480() {
	return _480;
    }

    public void set_480(Float _480) {
	this._480 = _480;
    }

    public Float get_481() {
	return _481;
    }

    public void set_481(Float _481) {
	this._481 = _481;
    }

    public Float get_482() {
	return _482;
    }

    public void set_482(Float _482) {
	this._482 = _482;
    }

    public Float get_401() {
	return _401;
    }

    public void set_401(Float _401) {
	this._401 = _401;
    }

    public Float get_402() {
	return _402;
    }

    public void set_402(Float _402) {
	this._402 = _402;
    }

    public Float get_403() {
	return _403;
    }

    public void set_403(Float _403) {
	this._403 = _403;
    }

    public Float get_404() {
	return _404;
    }

    public void set_404(Float _404) {
	this._404 = _404;
    }

    public Float get_405() {
	return _405;
    }

    public void set_405(Float _405) {
	this._405 = _405;
    }

    public Float get_406() {
	return _406;
    }

    public void set_406(Float _406) {
	this._406 = _406;
    }

    public Float get_407() {
	return _407;
    }

    public void set_407(Float _407) {
	this._407 = _407;
    }

    public Float get_408() {
	return _408;
    }

    public void set_408(Float _408) {
	this._408 = _408;
    }

    public Float get_413() {
	return _413;
    }

    public void set_413(Float _413) {
	this._413 = _413;
    }

    public Float get_414() {
	return _414;
    }

    public void set_414(Float _414) {
	this._414 = _414;
    }

    public Float get_415() {
	return _415;
    }

    public void set_415(Float _415) {
	this._415 = _415;
    }

    public Float get_416() {
	return _416;
    }

    public void set_416(Float _416) {
	this._416 = _416;
    }

    public Float get_425() {
	return _425;
    }

    public void set_425(Float _425) {
	this._425 = _425;
    }

    public Float get_426() {
	return _426;
    }

    public void set_426(Float _426) {
	this._426 = _426;
    }

    public Float get_501() {
	return _501;
    }

    public void set_501(Float _501) {
	this._501 = _501;
    }

    public Float get_502() {
	return _502;
    }

    public void set_502(Float _502) {
	this._502 = _502;
    }

    public Float get_503() {
	return _503;
    }

    public void set_503(Float _503) {
	this._503 = _503;
    }

    public Float get_504() {
	return _504;
    }

    public void set_504(Float _504) {
	this._504 = _504;
    }

    public Float get_505() {
	return _505;
    }

    public void set_505(Float _505) {
	this._505 = _505;
    }

    public Float get_506() {
	return _506;
    }

    public void set_506(Float _506) {
	this._506 = _506;
    }

    public Float get_507() {
	return _507;
    }

    public void set_507(Float _507) {
	this._507 = _507;
    }

    public Float get_508() {
	return _508;
    }

    public void set_508(Float _508) {
	this._508 = _508;
    }

    public Float get_511() {
	return _511;
    }

    public void set_511(Float _511) {
	this._511 = _511;
    }

    public Float get_512() {
	return _512;
    }

    public void set_512(Float _512) {
	this._512 = _512;
    }

    public Float get_515() {
	return _515;
    }

    public void set_515(Float _515) {
	this._515 = _515;
    }

    public Float get_516() {
	return _516;
    }

    public void set_516(Float _516) {
	this._516 = _516;
    }

    public Float get_517() {
	return _517;
    }

    public void set_517(Float _517) {
	this._517 = _517;
    }

    public Float get_518() {
	return _518;
    }

    public void set_518(Float _518) {
	this._518 = _518;
    }

    public Float get_103() {
	return _103;
    }

    public void set_103(Float _103) {
	this._103 = _103;
    }

    public Float get_104() {
	return _104;
    }

    public void set_104(Float _104) {
	this._104 = _104;
    }

    public Float get_121() {
	return _121;
    }

    public void set_121(Float _121) {
	this._121 = _121;
    }

    public Float get_122() {
	return _122;
    }

    public void set_122(Float _122) {
	this._122 = _122;
    }

    public Float get_105() {
	return _105;
    }

    public void set_105(Float _105) {
	this._105 = _105;
    }

    public Float get_106() {
	return _106;
    }

    public void set_106(Float _106) {
	this._106 = _106;
    }

    public Float get_107() {
	return _107;
    }

    public void set_107(Float _107) {
	this._107 = _107;
    }

    public Float get_108() {
	return _108;
    }

    public void set_108(Float _108) {
	this._108 = _108;
    }

    public Float get_109() {
	return _109;
    }

    public void set_109(Float _109) {
	this._109 = _109;
    }

    public Float get_110() {
	return _110;
    }

    public void set_110(Float _110) {
	this._110 = _110;
    }

    public Float get_101() {
	return _101;
    }

    public void set_101(Float _101) {
	this._101 = _101;
    }

    public Float get_102() {
	return _102;
    }

    public void set_102(Float _102) {
	this._102 = _102;
    }

    public Float get_909() {
	return _909;
    }

    public void set_909(Float _909) {
	this._909 = _909;
    }

    public Float get_910() {
	return _910;
    }

    public void set_910(Float _910) {
	this._910 = _910;
    }

    public Float get_111() {
	return _111;
    }

    public void set_111(Float _111) {
	this._111 = _111;
    }

    public Float get_112() {
	return _112;
    }

    public void set_112(Float _112) {
	this._112 = _112;
    }

    public Float get_113() {
	return _113;
    }

    public void set_113(Float _113) {
	this._113 = _113;
    }

    public Float get_114() {
	return _114;
    }

    public void set_114(Float _114) {
	this._114 = _114;
    }

    public Float get_129() {
	return _129;
    }

    public void set_129(Float _129) {
	this._129 = _129;
    }

    public Float get_130() {
	return _130;
    }

    public void set_130(Float _130) {
	this._130 = _130;
    }

    public Float get_143() {
	return _143;
    }

    public void set_143(Float _143) {
	this._143 = _143;
    }

    public Float get_144() {
	return _144;
    }

    public void set_144(Float _144) {
	this._144 = _144;
    }

    public Float get_145() {
	return _145;
    }

    public void set_145(Float _145) {
	this._145 = _145;
    }

    public Float get_146() {
	return _146;
    }

    public void set_146(Float _146) {
	this._146 = _146;
    }

    public Float get_147() {
	return _147;
    }

    public void set_147(Float _147) {
	this._147 = _147;
    }

    public Float get_148() {
	return _148;
    }

    public void set_148(Float _148) {
	this._148 = _148;
    }

    public Float get_141() {
	return _141;
    }

    public void set_141(Float _141) {
	this._141 = _141;
    }

    public Float get_142() {
	return _142;
    }

    public void set_142(Float _142) {
	this._142 = _142;
    }

    public Float get_701() {
	return _701;
    }

    public void set_701(Float _701) {
	this._701 = _701;
    }

    public Float get_702() {
	return _702;
    }

    public void set_702(Float _702) {
	this._702 = _702;
    }

    public Float get_123() {
	return _123;
    }

    public void set_123(Float _123) {
	this._123 = _123;
    }

    public Float get_124() {
	return _124;
    }

    public void set_124(Float _124) {
	this._124 = _124;
    }

    public Float get_125() {
	return _125;
    }

    public void set_125(Float _125) {
	this._125 = _125;
    }

    public Float get_126() {
	return _126;
    }

    public void set_126(Float _126) {
	this._126 = _126;
    }

    public Float get_151() {
	return _151;
    }

    public void set_151(Float _151) {
	this._151 = _151;
    }

    public Float get_152() {
	return _152;
    }

    public void set_152(Float _152) {
	this._152 = _152;
    }

    public Float get_163() {
	return _163;
    }

    public void set_163(Float _163) {
	this._163 = _163;
    }

    public Float get_164() {
	return _164;
    }

    public void set_164(Float _164) {
	this._164 = _164;
    }

    public Float get_165() {
	return _165;
    }

    public void set_165(Float _165) {
	this._165 = _165;
    }

    public Float get_166() {
	return _166;
    }

    public void set_166(Float _166) {
	this._166 = _166;
    }

    public Float get_159() {
	return _159;
    }

    public void set_159(Float _159) {
	this._159 = _159;
    }

    public Float get_160() {
	return _160;
    }

    public void set_160(Float _160) {
	this._160 = _160;
    }

    public Float get_175() {
	return _175;
    }

    public void set_175(Float _175) {
	this._175 = _175;
    }

    public Float get_176() {
	return _176;
    }

    public void set_176(Float _176) {
	this._176 = _176;
    }

    public Float get_131() {
	return _131;
    }

    public void set_131(Float _131) {
	this._131 = _131;
    }

    public Float get_132() {
	return _132;
    }

    public void set_132(Float _132) {
	this._132 = _132;
    }

    public Float get_133() {
	return _133;
    }

    public void set_133(Float _133) {
	this._133 = _133;
    }

    public Float get_134() {
	return _134;
    }

    public void set_134(Float _134) {
	this._134 = _134;
    }

    public Float get_741() {
	return _741;
    }

    public void set_741(Float _741) {
	this._741 = _741;
    }

    public Float get_742() {
	return _742;
    }

    public void set_742(Float _742) {
	this._742 = _742;
    }

    public Float get_291() {
	return _291;
    }

    public void set_291(Float _291) {
	this._291 = _291;
    }

    public Float get_292() {
	return _292;
    }

    public void set_292(Float _292) {
	this._292 = _292;
    }

    public Float get_389() {
	return _389;
    }

    public void set_389(Float _389) {
	this._389 = _389;
    }

    public Float get_390() {
	return _390;
    }

    public void set_390(Float _390) {
	this._390 = _390;
    }

    public Float get_391() {
	return _391;
    }

    public void set_391(Float _391) {
	this._391 = _391;
    }

    public Float get_392() {
	return _392;
    }

    public void set_392(Float _392) {
	this._392 = _392;
    }

    public Float get_463() {
	return _463;
    }

    public void set_463(Float _463) {
	this._463 = _463;
    }

    public Float get_464() {
	return _464;
    }

    public void set_464(Float _464) {
	this._464 = _464;
    }

    public Float get_471() {
	return _471;
    }

    public void set_471(Float _471) {
	this._471 = _471;
    }

    public Float get_472() {
	return _472;
    }

    public void set_472(Float _472) {
	this._472 = _472;
    }

    public Float get_411() {
	return _411;
    }

    public void set_411(Float _411) {
	this._411 = _411;
    }

    public Float get_412() {
	return _412;
    }

    public void set_412(Float _412) {
	this._412 = _412;
    }

    public Float get_421() {
	return _421;
    }

    public void set_421(Float _421) {
	this._421 = _421;
    }

    public Float get_422() {
	return _422;
    }

    public void set_422(Float _422) {
	this._422 = _422;
    }

    public Float get_509() {
	return _509;
    }

    public void set_509(Float _509) {
	this._509 = _509;
    }

    public Float get_510() {
	return _510;
    }

    public void set_510(Float _510) {
	this._510 = _510;
    }

    public Float get_513() {
	return _513;
    }

    public void set_513(Float _513) {
	this._513 = _513;
    }

    public Float get_514() {
	return _514;
    }

    public void set_514(Float _514) {
	this._514 = _514;
    }

    public Float get_295() {
	return _295;
    }

    public void set_295(Float _295) {
	this._295 = _295;
    }

    public Float get_296() {
	return _296;
    }

    public void set_296(Float _296) {
	this._296 = _296;
    }

    public Float get_171() {
	return _171;
    }

    public void set_171(Float _171) {
	this._171 = _171;
    }

    public Float get_172() {
	return _172;
    }

    public void set_172(Float _172) {
	this._172 = _172;
    }

    public Float get_173() {
	return _173;
    }

    public void set_173(Float _173) {
	this._173 = _173;
    }

    public Float get_174() {
	return _174;
    }

    public void set_174(Float _174) {
	this._174 = _174;
    }

    public Float get_395() {
	return _395;
    }

    public void set_395(Float _395) {
	this._395 = _395;
    }

    public Float get_396() {
	return _396;
    }

    public void set_396(Float _396) {
	this._396 = _396;
    }

    public String getAgrLocation1() {
	return this.agrLocation1;
    }

    public void setAgrLocation1(String agrLocation1) {
	this.agrLocation1 = agrLocation1;
    }

    public String getAgrProdKind1() {
	return this.agrProdKind1;
    }

    public void setAgrProdKind1(String agrProdKind1) {
	this.agrProdKind1 = agrProdKind1;
    }

    public Float getAgrPopulation1() {
	return this.agrPopulation1;
    }

    public void setAgrPopulation1(Float agrPopulation1) {
	this.agrPopulation1 = agrPopulation1;
    }

    public Integer getAgrLocationType1() {
	return this.agrLocationType1;
    }

    public void setAgrLocationType1(Integer agrLocationType1) {
	this.agrLocationType1 = agrLocationType1;
    }

    public Integer getAgrHasWater1() {
	return this.agrHasWater1;
    }

    public void setAgrHasWater1(Integer agrHasWater1) {
	this.agrHasWater1 = agrHasWater1;
    }

    public Float getAgrNetIncome1() {
	return this.agrNetIncome1;
    }

    public void setAgrNetIncome1(Float agrNetIncome1) {
	this.agrNetIncome1 = agrNetIncome1;
    }

    public Float getAgrTotalNetincome1() {
	return this.agrTotalNetincome1;
    }

    public void setAgrTotalNetincome1(Float agrTotalNetincome1) {
	this.agrTotalNetincome1 = agrTotalNetincome1;
    }

    public Float getAgrTotalWifeNetincome1() {
	return this.agrTotalWifeNetincome1;
    }

    public void setAgrTotalWifeNetincome1(Float agrTotalWifeNetincome1) {
	this.agrTotalWifeNetincome1 = agrTotalWifeNetincome1;
    }

    public String getAgrLocation2() {
	return this.agrLocation2;
    }

    public void setAgrLocation2(String agrLocation2) {
	this.agrLocation2 = agrLocation2;
    }

    public String getAgrProdKind2() {
	return this.agrProdKind2;
    }

    public void setAgrProdKind2(String agrProdKind2) {
	this.agrProdKind2 = agrProdKind2;
    }

    public Float getAgrPopulation2() {
	return this.agrPopulation2;
    }

    public void setAgrPopulation2(Float agrPopulation2) {
	this.agrPopulation2 = agrPopulation2;
    }

    public Integer getAgrLocationType2() {
	return this.agrLocationType2;
    }

    public void setAgrLocationType2(Integer agrLocationType2) {
	this.agrLocationType2 = agrLocationType2;
    }

    public Integer getAgrHasWater2() {
	return this.agrHasWater2;
    }

    public void setAgrHasWater2(Integer agrHasWater2) {
	this.agrHasWater2 = agrHasWater2;
    }

    public Float getAgrNetIncome2() {
	return this.agrNetIncome2;
    }

    public void setAgrNetIncome2(Float agrNetIncome2) {
	this.agrNetIncome2 = agrNetIncome2;
    }

    public Float getAgrTotalNetincome2() {
	return this.agrTotalNetincome2;
    }

    public void setAgrTotalNetincome2(Float agrTotalNetincome2) {
	this.agrTotalNetincome2 = agrTotalNetincome2;
    }

    public Float getAgrTotalWifeNetincome2() {
	return this.agrTotalWifeNetincome2;
    }

    public void setAgrTotalWifeNetincome2(Float agrTotalWifeNetincome2) {
	this.agrTotalWifeNetincome2 = agrTotalWifeNetincome2;
    }

    public String getAgrLocation3() {
	return this.agrLocation3;
    }

    public void setAgrLocation3(String agrLocation3) {
	this.agrLocation3 = agrLocation3;
    }

    public String getAgrProdKind3() {
	return this.agrProdKind3;
    }

    public void setAgrProdKind3(String agrProdKind3) {
	this.agrProdKind3 = agrProdKind3;
    }

    public Float getAgrPopulation3() {
	return this.agrPopulation3;
    }

    public void setAgrPopulation3(Float agrPopulation3) {
	this.agrPopulation3 = agrPopulation3;
    }

    public Integer getAgrLocationType3() {
	return this.agrLocationType3;
    }

    public void setAgrLocationType3(Integer agrLocationType3) {
	this.agrLocationType3 = agrLocationType3;
    }

    public Integer getAgrHasWater3() {
	return this.agrHasWater3;
    }

    public void setAgrHasWater3(Integer agrHasWater3) {
	this.agrHasWater3 = agrHasWater3;
    }

    public Float getAgrNetIncome3() {
	return this.agrNetIncome3;
    }

    public void setAgrNetIncome3(Float agrNetIncome3) {
	this.agrNetIncome3 = agrNetIncome3;
    }

    public Float getAgrTotalNetincome3() {
	return this.agrTotalNetincome3;
    }

    public void setAgrTotalNetincome3(Float agrTotalNetincome3) {
	this.agrTotalNetincome3 = agrTotalNetincome3;
    }

    public Float getAgrTotalWifeNetincome3() {
	return this.agrTotalWifeNetincome3;
    }

    public void setAgrTotalWifeNetincome3(Float agrTotalWifeNetincome3) {
	this.agrTotalWifeNetincome3 = agrTotalWifeNetincome3;
    }

    public String getAgrLocation4() {
	return this.agrLocation4;
    }

    public void setAgrLocation4(String agrLocation4) {
	this.agrLocation4 = agrLocation4;
    }

    public String getAgrProdKind4() {
	return this.agrProdKind4;
    }

    public void setAgrProdKind4(String agrProdKind4) {
	this.agrProdKind4 = agrProdKind4;
    }

    public Float getAgrPopulation4() {
	return this.agrPopulation4;
    }

    public void setAgrPopulation4(Float agrPopulation4) {
	this.agrPopulation4 = agrPopulation4;
    }

    public Integer getAgrLocationType4() {
	return this.agrLocationType4;
    }

    public void setAgrLocationType4(Integer agrLocationType4) {
	this.agrLocationType4 = agrLocationType4;
    }

    public Integer getAgrHasWater4() {
	return this.agrHasWater4;
    }

    public void setAgrHasWater4(Integer agrHasWater4) {
	this.agrHasWater4 = agrHasWater4;
    }

    public Float getAgrNetIncome4() {
	return this.agrNetIncome4;
    }

    public void setAgrNetIncome4(Float agrNetIncome4) {
	this.agrNetIncome4 = agrNetIncome4;
    }

    public Float getAgrTotalNetincome4() {
	return this.agrTotalNetincome4;
    }

    public void setAgrTotalNetincome4(Float agrTotalNetincome4) {
	this.agrTotalNetincome4 = agrTotalNetincome4;
    }

    public Float getAgrTotalWifeNetincome4() {
	return this.agrTotalWifeNetincome4;
    }

    public void setAgrTotalWifeNetincome4(Float agrTotalWifeNetincome4) {
	this.agrTotalWifeNetincome4 = agrTotalWifeNetincome4;
    }

    public Set<E1> getE1s() {
	return this.e1s;
    }

    public void setE1s(Set<E1> e1s) {
	this.e1s = e1s;
    }

}