package gr.manousos.model;

// Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E1taxPayerBankAccount generated by hbm2java
 */
@XmlRootElement
public class E1taxPayerBankAccount implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private E1Id id;
    private E1 e1;
    private String bic;
    private String iban;

    public E1taxPayerBankAccount() {
    }

    public E1taxPayerBankAccount(E1 e1) {
	this.e1 = e1;
    }

    public E1taxPayerBankAccount(E1 e1, String bic, String iban) {
	this.e1 = e1;
	this.bic = bic;
	this.iban = iban;
    }

    public E1Id getId() {
	return this.id;
    }

    public void setId(E1Id id) {
	this.id = id;
    }

    public E1 getE1() {
	return this.e1;
    }

    public void setE1(E1 e1) {
	this.e1 = e1;
    }

    public String getBic() {
	return this.bic;
    }

    public void setBic(String bic) {
	this.bic = bic;
    }

    public String getIban() {
	return this.iban;
    }

    public void setIban(String iban) {
	this.iban = iban;
    }

}
