package gr.manousos.model;

// Generated 17 Ιαν 2013 11:03:44 μμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E2 generated by hbm2java
 */
@XmlRootElement
public class E2 implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private E2Id id;
	private Taxpayer taxpayer;
	private Integer isComplete;
	private Set<E2otherEstate> e2otherEstates = new HashSet<E2otherEstate>(0);
	private Set<E2estate> e2estates = new HashSet<E2estate>(0);

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public int getTaxierID() {
		return TaxierID;
	}

	public void setTaxierID(int taxierID) {
		TaxierID = taxierID;
	}

	private int year;
	private int TaxierID;

	public E2() {
	}

	public E2(int TaxierID, int year, Integer isComplete) {
		this.TaxierID = TaxierID;
		this.year = year;
		this.isComplete = isComplete;
	}

	public E2(E2Id id, Taxpayer taxpayer) {
		this.id = id;
		this.taxpayer = taxpayer;
	}

	public E2(E2Id id, Taxpayer taxpayer, Integer isComplete,
			Set<E2otherEstate> e2otherEstates, Set<E2estate> e2estates) {
		this.id = id;
		this.taxpayer = taxpayer;
		this.isComplete = isComplete;
		this.e2otherEstates = e2otherEstates;
		this.e2estates = e2estates;
	}

	public E2Id getId() {
		return this.id;
	}

	public void setId(E2Id id) {
		this.id = id;
	}

	public Taxpayer getTaxpayer() {
		return this.taxpayer;
	}

	public void setTaxpayer(Taxpayer taxpayer) {
		this.taxpayer = taxpayer;
	}

	public Integer getIsComplete() {
		return this.isComplete;
	}

	public void setIsComplete(Integer isComplete) {
		this.isComplete = isComplete;
	}

	public Set<E2otherEstate> getE2otherEstates() {
		return this.e2otherEstates;
	}

	public void setE2otherEstates(Set<E2otherEstate> e2otherEstates) {
		this.e2otherEstates = e2otherEstates;
	}

	public Set<E2estate> getE2estates() {
		return this.e2estates;
	}

	public void setE2estates(Set<E2estate> e2estates) {
		this.e2estates = e2estates;
	}

}
