package gr.manousos.model;

// Generated 3 Μαρ 2013 10:07:00 μμ by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * E2 generated by hbm2java
 */
@XmlRootElement
public class E2 implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private E2Id id;
	private Taxpayer taxpayer;
	private Integer isComplete;
	private Date dateInserted;
	private Set<E2otherEstate> e2otherEstates = new HashSet<E2otherEstate>(0);
	private Set<E2estate> e2estates = new HashSet<E2estate>(0);

	public E2() {
	}

	public E2(E2Id id, Taxpayer taxpayer) {
		this.id = id;
		this.taxpayer = taxpayer;
	}

	public E2(E2Id id, Taxpayer taxpayer, Integer isComplete,
			Date dateInserted, Set<E2otherEstate> e2otherEstates,
			Set<E2estate> e2estates) {
		this.id = id;
		this.taxpayer = taxpayer;
		this.isComplete = isComplete;
		this.dateInserted = dateInserted;
		this.e2otherEstates = e2otherEstates;
		this.e2estates = e2estates;
	}

	public E2Id getId() {
		return this.id;
	}

	public void setId(E2Id id) {
		this.id = id;
	}

	public Taxpayer getTaxpayer() {
		return this.taxpayer;
	}

	public void setTaxpayer(Taxpayer taxpayer) {
		this.taxpayer = taxpayer;
	}

	public Integer getIsComplete() {
		return this.isComplete;
	}

	public void setIsComplete(Integer isComplete) {
		this.isComplete = isComplete;
	}

	public Date getDateInserted() {
		return this.dateInserted;
	}

	public void setDateInserted(Date dateInserted) {
		this.dateInserted = dateInserted;
	}

	public Set<E2otherEstate> getE2otherEstates() {
		return this.e2otherEstates;
	}

	public void setE2otherEstates(Set<E2otherEstate> e2otherEstates) {
		this.e2otherEstates = e2otherEstates;
	}

	public Set<E2estate> getE2estates() {
		return this.e2estates;
	}

	public void setE2estates(Set<E2estate> e2estates) {
		this.e2estates = e2estates;
	}

}
