package gr.manousos.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated 17 Ιαν 2013 11:03:44 μμ by Hibernate Tools 3.4.0.CR1

/**
 * E2coOwner generated by hbm2java
 */
@XmlRootElement
public class E2coOwner implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private E2estate e2estate;
	private String fullName;
	private String afm;
	private String address;
	private float percent;
	private Float rent;

	/**
	 * Transient fields
	 */
	private String location;
	private String position;
	private String usage;
	private float area;
	

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getUsage() {
		return usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public float getArea() {
		return area;
	}

	public void setArea(float area) {
		this.area = area;
	}

	/**
	 * END Transient fields
	 */
	public E2coOwner() {
	}

	public E2coOwner(E2estate e2estate, String fullName, String afm,
			String address, float percent) {
		this.e2estate = e2estate;
		this.fullName = fullName;
		this.afm = afm;
		this.address = address;
		this.percent = percent;
	}

	public E2coOwner(E2estate e2estate, String fullName, String afm,
			String address, float percent, Float rent) {
		this.e2estate = e2estate;
		this.fullName = fullName;
		this.afm = afm;
		this.address = address;
		this.percent = percent;
		this.rent = rent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public E2estate getE2estate() {
		return this.e2estate;
	}

	public void setE2estate(E2estate e2estate) {
		this.e2estate = e2estate;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getAfm() {
		return this.afm;
	}

	public void setAfm(String afm) {
		this.afm = afm;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public float getPercent() {
		return this.percent;
	}

	public void setPercent(float percent) {
		this.percent = percent;
	}

	public Float getRent() {
		return this.rent;
	}

	public void setRent(Float rent) {
		this.rent = rent;
	}

}
