package gr.manousos.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated 23 Απρ 2013 9:07:59 μμ by Hibernate Tools 3.4.0.CR1

/**
 * IncomeTaxId generated by hbm2java
 */
@XmlRootElement
public class IncomeTaxId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int taxPayerId;
    private int year;

    public IncomeTaxId() {
    }

    public IncomeTaxId(int taxPayerId, int year) {
	this.taxPayerId = taxPayerId;
	this.year = year;
    }

    public int getTaxPayerId() {
	return this.taxPayerId;
    }

    public void setTaxPayerId(int taxPayerId) {
	this.taxPayerId = taxPayerId;
    }

    public int getYear() {
	return this.year;
    }

    public void setYear(int year) {
	this.year = year;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof IncomeTaxId))
	    return false;
	IncomeTaxId castOther = (IncomeTaxId) other;

	return (this.getTaxPayerId() == castOther.getTaxPayerId())
		&& (this.getYear() == castOther.getYear());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getTaxPayerId();
	result = 37 * result + this.getYear();
	return result;
    }

}
