package gr.manousos.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated 23 Απρ 2013 9:07:59 μμ by Hibernate Tools 3.4.0.CR1

/**
 * IncomeTax generated by hbm2java
 */
@XmlRootElement
public class IncomeTax implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private IncomeTaxId id;
    private E1 e1;
    private Float principalTax;
    private Float wifeTax;

    public IncomeTax() {
    }

    public IncomeTax(IncomeTaxId id) {
	this.id = id;
    }

    public IncomeTax(IncomeTaxId id, Float principalTax, Float wifeTax) {
	this.id = id;
	this.principalTax = principalTax;
	this.wifeTax = wifeTax;
    }

    public IncomeTaxId getId() {
	return this.id;
    }

    public void setId(IncomeTaxId id) {
	this.id = id;
    }

    public E1 getE1() {
	return this.e1;
    }

    public void setE1(E1 e1) {
	this.e1 = e1;
    }

    public Float getPrincipalTax() {
	return this.principalTax;
    }

    public void setPrincipalTax(Float principalTax) {
	this.principalTax = principalTax;
    }

    public Float getWifeTax() {
	return this.wifeTax;
    }

    public void setWifeTax(Float wifeTax) {
	this.wifeTax = wifeTax;
    }

}
