package gr.manousos.model;

// Generated 2 Μαρ 2013 9:35:29 μμ by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * RelatePerson generated by hbm2java
 */
@XmlRootElement
public class RelatePerson implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idRelatePerson;
	private Contact contact;
	private Integer type;
	private String address;
	private String afm;
	private String fname;
	private String lname;
	private String fatherName;
	private Set<E1relatePersons> e1relatePersonses = new HashSet<E1relatePersons>(
			0);

	public RelatePerson() {
	}

	public RelatePerson(int idRelatePerson) {
		this.idRelatePerson = idRelatePerson;
	}

	public RelatePerson(int idRelatePerson, Contact contact, Integer type,
			String address, String afm, String fname, String lname,
			String fatherName, Set<E1relatePersons> e1relatePersonses) {
		this.idRelatePerson = idRelatePerson;
		this.contact = contact;
		this.type = type;
		this.address = address;
		this.afm = afm;
		this.fname = fname;
		this.lname = lname;
		this.fatherName = fatherName;
		this.e1relatePersonses = e1relatePersonses;
	}

	public int getIdRelatePerson() {
		return this.idRelatePerson;
	}

	public void setIdRelatePerson(int idRelatePerson) {
		this.idRelatePerson = idRelatePerson;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAfm() {
		return this.afm;
	}

	public void setAfm(String afm) {
		this.afm = afm;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public Set<E1relatePersons> getE1relatePersonses() {
		return this.e1relatePersonses;
	}

	public void setE1relatePersonses(Set<E1relatePersons> e1relatePersonses) {
		this.e1relatePersonses = e1relatePersonses;
	}

}
