package gr.manousos.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1

/**
 * RelatePerson generated by hbm2java
 */
@XmlRootElement
public class RelatePerson implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idRelatePerson;
	private Contact contact;
	private Address address;
	private Integer type;
	private String afm;
	private String fname;
	private String lname;
	private String fatherName;

	public RelatePerson() {
	}

	public RelatePerson(int idRelatePerson) {
		this.idRelatePerson = idRelatePerson;
	}

	public RelatePerson(int idRelatePerson, Contact contact, Address address,
			Integer type, String afm, String fname, String lname,
			String fatherName) {
		this.idRelatePerson = idRelatePerson;
		this.contact = contact;
		this.address = address;
		this.type = type;
		this.afm = afm;
		this.fname = fname;
		this.lname = lname;
		this.fatherName = fatherName;
	}

	public int getIdRelatePerson() {
		return this.idRelatePerson;
	}

	public void setIdRelatePerson(int idRelatePerson) {
		this.idRelatePerson = idRelatePerson;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getAfm() {
		return this.afm;
	}

	public void setAfm(String afm) {
		this.afm = afm;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

}
