package gr.manousos.model;

import javax.xml.bind.annotation.XmlRootElement;


// default package
// Generated 11 Νοε 2012 6:37:01 μμ by Hibernate Tools 3.4.0.CR1

/**
 * Taxpayer generated by hbm2java
 */
@XmlRootElement
public class Taxpayer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Contact contact;
	private User user;
	private String afm;
	private String fname;
	private String lname;
	private String fatherName;

	public Taxpayer() {
	}

	public Taxpayer(Contact contact, User user, String afm, String fname,
			String lname, String fatherName) {
		this.contact = contact;
		this.user = user;
		this.afm = afm;
		this.fname = fname;
		this.lname = lname;
		this.fatherName = fatherName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAfm() {
		return this.afm;
	}

	public void setAfm(String afm) {
		this.afm = afm;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

}
